/// <reference path="../pb_data/types.d.ts" />
/**
 * The deadline engine. One engine for every dated obligation that follows an
 * event: trademark and design prosecution and renewals, copyright
 * registration and termination windows, talent playbooks, Content ID
 * clocks, enforcement and customs periods.
 *
 * Principles:
 * - rules are data (collection `rules`), versioned by effective date;
 * - calendar-month arithmetic, never day counts; business-day offsets count
 *   the office's working days (lib_calendar.addBusinessDays);
 * - closure-day roll-forward by the office where the act is due;
 * - every computed date carries its bilingual explanation (calculation.steps,
 *   each { en, ja }) and citation, so the UI can answer "Why this date?";
 * - preview before creating, diff before regenerating, never duplicate
 *   (deadlines carry a stable `key`), never delete (close with a reason);
 * - a person can lock a date; locked dates are never recomputed.
 *
 * Obligations that come from a record's own fields (agreement terms,
 * committee calendars, product sales windows, approval SLAs, permission
 * expiries) are generated by lib_obligations.js, not by rules.
 */

/** Subject types: collection and the relation field on deadlines/events. */
const SUBJECTS = {
  matter: { coll: 'matters', field: 'matter' },
  agreement: { coll: 'agreements', field: 'agreement' },
  work: { coll: 'titles', field: 'work' },
  character: { coll: 'characters', field: 'character' },
  talent: { coll: 'talents', field: 'talent' },
  product: { coll: 'products', field: 'product' },
  approval: { coll: 'approvals', field: 'approval' },
  permission: { coll: 'permissions', field: 'permission' },
  committee: { coll: 'committees', field: 'committee' },
  case: { coll: 'enforcement_cases', field: 'case_ref' },
  registration: { coll: 'society_registrations', field: 'registration' },
  claim: { coll: 'content_id_claims', field: 'claim' },
  recordation: { coll: 'customs_recordations', field: 'recordation' },
  society_contract: { coll: 'society_contracts', field: 'society_contract' },
  fan_registration: { coll: 'fan_registrations', field: 'fan_registration' },
  enrollment: { coll: 'platform_enrollments', field: 'enrollment' },
};

/**
 * Event codes. `subjects` lists where each can be recorded. `status` is the
 * subject status it sets (matters: the matter status; talents: lifecycle;
 * claims and cases: status). `field` is a date field it fills when empty.
 */
const EVENT_CODES = {
  // Trademarks and designs.
  FILED: { label: 'Application filed', label_ja: '出願', subjects: ['matter'], status: 'filed', field: 'filing_date' },
  PUBLISHED: { label: 'Application published', label_ja: '出願公開・公告', subjects: ['matter'], status: 'published', field: 'publication_date' },
  OA_ISSUED: { label: 'Office action or notice of refusal', label_ja: '拒絶理由通知・オフィスアクション', subjects: ['matter'], status: 'office_action' },
  RESPONSE_FILED: { label: 'Response filed', label_ja: '応答書提出', subjects: ['matter'], status: 'examination' },
  NOTICE_ALLOWANCE: { label: 'Notice of allowance or decision to register', label_ja: '登録査定・許可通知', subjects: ['matter'], status: 'allowed' },
  REGISTERED: { label: 'Registered', label_ja: '設定登録', subjects: ['matter'], status: 'registered', field: 'registration_date' },
  GAZETTE_PUBLISHED: { label: 'Registration gazette published', label_ja: '登録公報発行', subjects: ['matter'], status: null },
  RENEWED: { label: 'Renewed', label_ja: '更新登録', subjects: ['matter'], status: 'registered' },
  ANNUITY_PAID: { label: 'Annual fee or second half paid', label_ja: '年金・後期分納付', subjects: ['matter'], status: null },
  DECLARATION_ACCEPTED: { label: 'Use declaration accepted', label_ja: '使用宣誓の受理', subjects: ['matter'], status: null },
  OPPOSITION_FILED: { label: 'Opposition filed', label_ja: '異議申立', subjects: ['matter'], status: 'opposed' },
  APPEAL_FILED: { label: 'Appeal filed', label_ja: '審判請求', subjects: ['matter'], status: 'examination' },
  REFUSED: { label: 'Refused (decision of refusal)', label_ja: '拒絶査定', subjects: ['matter'], status: 'refused' },
  ABANDONED: { label: 'Abandoned', label_ja: '放棄', subjects: ['matter'], status: 'abandoned' },
  WITHDRAWN: { label: 'Withdrawn', label_ja: '取下げ', subjects: ['matter'], status: 'withdrawn' },
  LAPSED: { label: 'Lapsed', label_ja: '消滅', subjects: ['matter'], status: 'lapsed' },
  EXPIRED: { label: 'Expired', label_ja: '存続期間満了', subjects: ['matter'], status: 'expired' },
  REVOKED: { label: 'Revoked', label_ja: '取消・無効', subjects: ['matter'], status: 'revoked' },
  CANCELLED: { label: 'Cancelled (non-use or other)', label_ja: '取消（不使用等）', subjects: ['matter'], status: 'cancelled' },
  ASSIGNED: { label: 'Assignment recorded', label_ja: '移転登録', subjects: ['matter'], status: null },
  // Titles and agreements.
  WORK_PUBLISHED: { label: 'First published or broadcast', label_ja: '最初の公表・放送', subjects: ['work'], status: null },
  AUTHOR_GRANT_EXECUTED: { label: 'Author grant executed', label_ja: '著作者による許諾の締結', subjects: ['agreement'], status: null },
  // Talents.
  DEBUT_SCHEDULED: { label: 'Debut scheduled', label_ja: 'デビュー予定', subjects: ['talent'], status: 'pre_debut' },
  DEBUTED: { label: 'Debuted', label_ja: 'デビュー', subjects: ['talent'], status: 'active' },
  HIATUS: { label: 'Hiatus started', label_ja: '活動休止', subjects: ['talent'], status: 'hiatus' },
  SUSPENDED: { label: 'Suspended', label_ja: '活動停止（謹慎）', subjects: ['talent'], status: 'suspended' },
  RESUMED: { label: 'Activity resumed', label_ja: '活動再開', subjects: ['talent'], status: 'active' },
  GRADUATION_SCHEDULED: { label: 'Graduation announced', label_ja: '卒業発表', subjects: ['talent'], status: 'graduation_announced' },
  GRADUATED: { label: 'Graduated', label_ja: '卒業', subjects: ['talent'], status: 'graduated' },
  TERMINATED: { label: 'Contract terminated', label_ja: '契約解除', subjects: ['talent'], status: 'terminated' },
  RECAST: { label: 'Role recast', label_ja: '演者交代', subjects: ['talent', 'character'], status: null },
  // Content ID.
  CID_DISPUTE_RECEIVED: { label: 'Dispute received', label_ja: '異議申し立て受領', subjects: ['claim'], status: 'disputed' },
  CID_APPEAL_RECEIVED: { label: 'Appeal received', label_ja: '再審査請求受領', subjects: ['claim'], status: 'appealed' },
  CID_RESOLVED: { label: 'Claim resolved', label_ja: '申し立て解決', subjects: ['claim'], status: 'resolved' },
  // Enforcement.
  PLATFORM_REQUEST_SENT: { label: 'Removal request sent to platform', label_ja: 'プラットフォームへ削除申出', subjects: ['case'], status: 'takedown_requested' },
  NOTICE_SENT: { label: 'Notice or warning sent', label_ja: '警告書・通知の送付', subjects: ['case'], status: 'notice_sent' },
  TAKEDOWN_CONFIRMED: { label: 'Content removed', label_ja: '削除確認', subjects: ['case'], status: 'removed' },
  COUNTER_NOTICE_RECEIVED: { label: 'Counter-notice received', label_ja: '反論通知受領', subjects: ['case'], status: 'counter_noticed' },
  CUSTOMS_SUSPENSION_NOTICE: { label: 'Customs verification notice', label_ja: '税関の認定手続開始通知', subjects: ['case'], status: 'investigating' },
  DETENTION_NOTICE: { label: 'Goods detained by customs', label_ja: '税関による貨物の留置・差止め', subjects: ['case'], status: 'investigating' },
  DISCLOSURE_REQUESTED: { label: 'Sender information disclosure requested', label_ja: '発信者情報開示請求', subjects: ['case'], status: 'disclosure_requested' },
  COMPLAINT_FILED: { label: 'Criminal complaint filed', label_ja: '刑事告訴', subjects: ['case'], status: 'complaint_filed' },
  SUIT_FILED: { label: 'Lawsuit filed', label_ja: '訴訟提起', subjects: ['case'], status: 'litigation' },
  SETTLED: { label: 'Settled', label_ja: '和解', subjects: ['case'], status: 'settled' },
  // Customs recordations.
  RECORDATION_ACCEPTED: { label: 'Recordation accepted', label_ja: '申立受理・備案', subjects: ['recordation'], status: 'accepted' },
  OTHER: { label: 'Other event', label_ja: 'その他', subjects: Object.keys(SUBJECTS), status: null },
};

const STATUS_GROUP = {
  to_file: 'pre_filing',
  filed: 'pending',
  published: 'pending',
  examination: 'pending',
  office_action: 'pending',
  allowed: 'pending',
  opposed: 'pending',
  registered: 'live',
  in_grace: 'live',
  lapsed: 'dead',
  abandoned: 'dead',
  withdrawn: 'dead',
  refused: 'dead',
  expired: 'dead',
  revoked: 'dead',
  cancelled: 'dead',
  transferred_out: 'dead',
};

const STATUTORY = { hard: true, extendable: true, designated: true };
const BASE_LABEL = {
  event_date: ['Event date', '事象の日'],
  filing_date: ['Filing date', '出願日'],
  priority_date: ['Earliest priority date', '最先の優先日'],
  publication_date: ['Publication date', '公開日・公告日'],
  registration_date: ['Registration date', '登録日'],
  expiry_date: ['Expiry date', '満了日'],
  signed_date: ['Agreement signature date', '契約締結日'],
  term_end: ['Agreement term end', '契約期間満了日'],
  graduation_date: ['Graduation date', '卒業日'],
  debut_date: ['Debut date', 'デビュー日'],
  valid_until: ['Valid until', '有効期限'],
  end_date: ['End date', '終了日'],
  documents_valid_until: ['Documents valid until', '書類の有効期限'],
};

function statusGroup(status) {
  return STATUS_GROUP[status] || 'pending';
}

function eventLabel(code) {
  const def = EVENT_CODES[code];
  return def ? { en: def.label, ja: def.label_ja } : { en: code, ja: code };
}

/* ------------------------------------------------------------------ */
/* Subjects                                                            */
/* ------------------------------------------------------------------ */

function subjectOf(app, type, id) {
  const u = require(`${__hooks}/lib_util.js`);
  const def = SUBJECTS[type];
  if (!def) return null;
  const rec = u.byId(app, def.coll, id);
  if (rec === null) return null;
  return subjectFromRecord(type, rec);
}

function subjectFromRecord(type, rec) {
  const s = {
    type: type,
    id: rec.id,
    record: rec,
    subject_type: type,
    jurisdiction: '*',
    route: '',
    label: '',
  };
  switch (type) {
    case 'matter':
      s.subject_type = rec.getString('ip_type');
      s.jurisdiction = rec.getString('jurisdiction').toUpperCase();
      s.route = rec.getString('route');
      s.label = rec.getString('ref') || rec.getString('title');
      break;
    case 'agreement':
      s.label = rec.getString('ref') || rec.getString('title');
      break;
    case 'work':
      s.jurisdiction = rec.getString('publication_country').toUpperCase() || '*';
      s.label = rec.getString('title');
      break;
    case 'talent':
      s.label = rec.getString('stage_name');
      break;
    case 'character':
    case 'product':
      s.label = rec.getString('name');
      break;
    case 'case':
      s.label = rec.getString('ref') || rec.getString('title');
      break;
    case 'recordation':
      s.jurisdiction = rec.getString('jurisdiction').toUpperCase();
      s.label = rec.getString('right_desc') || rec.getString('application_no');
      break;
    case 'claim':
      s.label = rec.getString('video_title') || rec.getString('video_url');
      break;
    case 'committee':
      s.label = rec.getString('name');
      break;
    default:
      s.label = rec.getString('title') || rec.getString('name') || rec.id;
  }
  return s;
}

function subjectEvents(app, subject) {
  const u = require(`${__hooks}/lib_util.js`);
  return u.findMany(app, 'events', SUBJECTS[subject.type].field + ' = {:id}', 'date', 0, { id: subject.id });
}

/* ------------------------------------------------------------------ */
/* Rules                                                               */
/* ------------------------------------------------------------------ */

function ruleObj(rec) {
  const u = require(`${__hooks}/lib_util.js`);
  return {
    id: rec.id,
    code: rec.getString('code'),
    name: rec.getString('name'),
    name_ja: rec.getString('name_ja'),
    subject_type: rec.getString('subject_type'),
    jurisdiction: rec.getString('jurisdiction').toUpperCase(),
    routes: u.j(rec, 'routes', []),
    trigger_event: rec.getString('trigger_event'),
    conditions: u.j(rec, 'conditions', {}),
    base: rec.getString('base'),
    oy: rec.getInt('offset_years'),
    om: rec.getInt('offset_months'),
    od: rec.getInt('offset_days'),
    business: rec.getString('offset_unit') === 'business',
    eom: rec.getBool('due_end_of_month'),
    kind: rec.getString('kind'),
    category: rec.getString('category') || 'other',
    title: rec.getString('title'),
    title_ja: rec.getString('title_ja') || rec.getString('title'),
    extensions: u.j(rec, 'extensions', []),
    final_offset_months: rec.getInt('final_offset_months'),
    final_offset_days: rec.getInt('final_offset_days'),
    window_months: rec.getInt('window_months'),
    grace_months: rec.getInt('grace_months'),
    grace_note: rec.getString('grace_note'),
    every: rec.getInt('recurring_years'),
    until: rec.getInt('recurring_until_years'),
    first: rec.getInt('recurring_first_cycle') || 1,
    cycle_label: rec.getString('cycle_label'),
    roll_office: rec.getString('roll_office').toUpperCase(),
    citation: rec.getString('citation'),
    notes: rec.getString('notes'),
    effective_from: u.d10(rec.getString('effective_from')),
    effective_to: u.d10(rec.getString('effective_to')),
    version: rec.getInt('version') || 1,
    creates_renewal: rec.getBool('creates_renewal'),
    fee_kind: rec.getString('fee_kind'),
  };
}

function candidateRules(app, code) {
  const u = require(`${__hooks}/lib_util.js`);
  return u.findMany(app, 'rules', 'enabled = true && trigger_event = {:c}', 'code', 0, { c: code }).map(ruleObj);
}

function externalIds(rec) {
  const u = require(`${__hooks}/lib_util.js`);
  const list = u.j(rec, 'external_ids', []);
  return Array.isArray(list) ? list : [];
}

function ruleMatches(app, rule, subject, eventDate, eventsCache, eventData) {
  const u = require(`${__hooks}/lib_util.js`);
  if (rule.subject_type !== subject.subject_type && rule.subject_type !== 'any') return false;
  const data = eventData || {};
  const jur = String(data.jurisdiction || subject.jurisdiction || '*').toUpperCase();
  if (rule.jurisdiction !== '*' && rule.jurisdiction !== jur) return false;
  if (rule.routes.length > 0 && rule.routes.indexOf(subject.route || 'national') < 0) return false;
  if (rule.effective_from && eventDate && eventDate < rule.effective_from) return false;
  if (rule.effective_to && eventDate && eventDate > rule.effective_to) return false;
  const c = rule.conditions || {};
  const rec = subject.record;
  if (c.first_filing === true && subject.type === 'matter') {
    const prios = u.j(rec, 'priority_claims', []);
    const rel = rec.getString('relation');
    if ((Array.isArray(prios) && prios.length > 0) || (rel !== '' && rel !== 'none') || rec.getString('parent') !== '') return false;
  }
  if (Array.isArray(c.not_routes) && c.not_routes.indexOf(subject.route) >= 0) return false;
  if (c.tm_register && subject.type === 'matter' && rec.getString('tm_register') !== '' && rec.getString('tm_register') !== c.tm_register) {
    return false;
  }
  if (c.option && subject.type === 'matter') {
    const opts = u.j(rec, 'options', {});
    if (!opts || opts[c.option] !== true) return false;
  }
  if (c.missing_external_id && subject.type === 'work') {
    for (const x of externalIds(rec)) if (x && x.type === c.missing_external_id && x.value) return false;
  }
  if (c.data_equals && typeof c.data_equals === 'object') {
    for (const k of Object.keys(c.data_equals)) if (String(data[k] || '') !== String(c.data_equals[k])) return false;
  }
  if (c.data_not && typeof c.data_not === 'object') {
    for (const k of Object.keys(c.data_not)) if (String(data[k] || '') === String(c.data_not[k])) return false;
  }
  if (c.stop_on_event && eventsCache) {
    for (const ev of eventsCache) if (ev.getString('code') === c.stop_on_event) return false;
  }
  return true;
}

/* ------------------------------------------------------------------ */
/* Date computation                                                    */
/* ------------------------------------------------------------------ */

function earliestPriority(rec) {
  const u = require(`${__hooks}/lib_util.js`);
  const list = [u.d10(rec.getString('filing_date'))];
  const prios = u.j(rec, 'priority_claims', []);
  if (Array.isArray(prios)) for (const p of prios) list.push(u.d10(p && p.date));
  return u.minDay(list);
}

/** Which record fields each base can read, per subject type. */
const BASE_FIELDS = {
  matter: {
    filing_date: 'filing_date',
    publication_date: 'publication_date',
    registration_date: 'registration_date',
    expiry_date: 'expiry_date',
  },
  agreement: { signed_date: 'signed_date', term_end: 'term_end' },
  talent: { graduation_date: 'graduation_date', debut_date: 'debut_date' },
  recordation: { valid_until: 'valid_until' },
  permission: { end_date: 'end_date' },
  fan_registration: { end_date: 'end_date' },
  enrollment: { documents_valid_until: 'documents_valid_until' },
};

function resolveBase(rule, subject, eventDate) {
  const u = require(`${__hooks}/lib_util.js`);
  const rec = subject.record;
  let base = '';
  const lbl = BASE_LABEL[rule.base] || ['Base date', '起算日'];
  let label = u.bi(lbl[0], lbl[1]);
  if (rule.base === 'priority_date' && subject.type === 'matter') base = earliestPriority(rec);
  else if (rule.base !== 'event_date') {
    const map = BASE_FIELDS[subject.type] || {};
    const f = map[rule.base];
    if (f) base = u.d10(rec.getString(f));
  }
  if (base === '') {
    base = u.d10(eventDate);
    if (rule.base !== 'event_date') {
      label = u.bi(lbl[0] + ' (not recorded yet, event date used)', lbl[1] + '（未登録のため事象の日を使用）');
    } else label = u.bi('Event date', '事象の日');
  }
  return { date: base, label: label };
}

function offsetText(y, m, d, business) {
  const en = [];
  const ja = [];
  if (y) {
    en.push(y + (Math.abs(y) === 1 ? ' year' : ' years'));
    ja.push(y + '年');
  }
  if (m) {
    en.push(m + (Math.abs(m) === 1 ? ' month' : ' months'));
    ja.push(m + 'か月');
  }
  if (d) {
    en.push(d + (business ? ' working' : '') + (Math.abs(d) === 1 ? ' day' : ' days'));
    ja.push(d + (business ? '執務日' : '日'));
  }
  return { en: en.length ? en.join(', ') : 'no offset', ja: ja.length ? ja.join('') : 'なし' };
}

function fill(template, cycle, every) {
  const n0 = every ? cycle * every : cycle;
  return String(template || '').split('{n}').join(String(cycle)).split('{n0}').join(String(n0));
}

function cycleTitle(rule, cycle) {
  return { en: fill(rule.title, cycle, rule.every), ja: fill(rule.title_ja || rule.title, cycle, rule.every) };
}

function cycleLabel(rule, cycle) {
  if (!rule.cycle_label) return '';
  return fill(rule.cycle_label, cycle, rule.every);
}

function rollOfficeFor(app, rule, subject, eventData) {
  const u = require(`${__hooks}/lib_util.js`);
  if (rule.roll_office) return rule.roll_office;
  if (subject.type === 'matter' || subject.type === 'recordation') return subject.jurisdiction;
  if (eventData && eventData.jurisdiction) return String(eventData.jurisdiction).toUpperCase();
  if (rule.business) return String(u.setting(app, 'work_calendar', 'JP') || 'JP').toUpperCase();
  return '';
}

/**
 * Compute every date for one rule application.
 * overrides: { period_months, period_days, due_date } for office-set periods.
 */
function computeRule(app, rule, subject, eventDate, cycle, overrides, bufferDays, eventData) {
  const u = require(`${__hooks}/lib_util.js`);
  const cal = require(`${__hooks}/lib_calendar.js`);
  const ov = overrides || {};
  const baseInfo = resolveBase(rule, subject, eventDate);
  const base = baseInfo.date;
  if (base === '') return null;
  const steps = [];
  steps.push(u.bi(baseInfo.label.en + ': ' + u.human(base) + '.', baseInfo.label.ja + '：' + u.humanJa(base) + '。'));
  const office = rollOfficeFor(app, rule, subject, eventData);

  const recurring = rule.every > 0;
  const extraYears = recurring ? (cycle - rule.first) * rule.every : 0;
  let nominal = '';
  if (rule.kind === 'designated' && u.d10(ov.due_date) !== '') {
    nominal = u.d10(ov.due_date);
    steps.push(u.bi('The office set the due date in the communication: ' + u.human(nominal) + '.', '通知書で官庁が指定した期限：' + u.humanJa(nominal) + '。'));
  } else if (rule.kind === 'designated' && Number(ov.period_months) > 0) {
    nominal = u.addYMD(base, 0, Number(ov.period_months), 0);
    steps.push(u.bi(
      'Period set by the office: ' + ov.period_months + ' months from the base date gives ' + u.human(nominal) + '.',
      '官庁指定の期間：起算日から' + ov.period_months + 'か月で' + u.humanJa(nominal) + '。',
    ));
  } else if (rule.kind === 'designated' && Number(ov.period_days) > 0) {
    nominal = u.addDays(base, Number(ov.period_days));
    steps.push(u.bi(
      'Period set by the office: ' + ov.period_days + ' days from the base date gives ' + u.human(nominal) + '.',
      '官庁指定の期間：起算日から' + ov.period_days + '日で' + u.humanJa(nominal) + '。',
    ));
  } else {
    const off = offsetText(rule.oy + extraYears, rule.om, rule.od, rule.business);
    if (rule.business && rule.od !== 0) {
      const mid = u.addYMD(base, rule.oy + extraYears, rule.om, 0);
      const bd = cal.addBusinessDays(app, office, mid, rule.od);
      nominal = bd.date;
      steps.push(u.bi(
        'Rule ' + rule.code + ' (v' + rule.version + '): ' + off.en + ' from the base date.',
        'ルール ' + rule.code + '（第' + rule.version + '版）：起算日から' + off.ja + '。',
      ));
      for (const s of bd.steps) steps.push(s);
    } else {
      nominal = u.addYMD(base, rule.oy + extraYears, rule.om, rule.od);
      const usual = rule.kind === 'designated';
      steps.push(u.bi(
        'Rule ' + rule.code + ' (v' + rule.version + '): ' + off.en + (rule.oy + rule.om + rule.od < 0 ? ' before' : ' after') + ' the base date gives ' + u.human(nominal) + '.' +
          (usual ? ' This is the usual period; confirm it against the communication.' : ''),
        'ルール ' + rule.code + '（第' + rule.version + '版）：起算日' + (rule.oy + rule.om + rule.od < 0 ? 'の' : 'から') + off.ja + (rule.oy + rule.om + rule.od < 0 ? '前' : '後') + 'は' + u.humanJa(nominal) + '。' +
          (usual ? '通常の期間です。通知書の記載を確認してください。' : ''),
      ));
    }
  }
  if (rule.eom) {
    const eom = u.endOfMonth(nominal);
    if (eom !== nominal) steps.push(u.bi('Due on the last day of that month: ' + u.human(eom) + '.', 'その月の末日が期限：' + u.humanJa(eom) + '。'));
    nominal = eom;
  }

  let due = nominal;
  if (STATUTORY[rule.kind] && office !== '' && office !== '*' && !rule.business) {
    const rolled = cal.rollForward(app, office, nominal);
    if (rolled.date !== nominal) {
      for (const s of rolled.steps) steps.push(s);
      steps.push(u.bi(
        'Moves to the next day the ' + cal.officeName(office) + ' is open: ' + u.human(rolled.date) + '.',
        cal.officeNameJa(office) + 'の次の開庁日に繰り延べ：' + u.humanJa(rolled.date) + '。',
      ));
      due = rolled.date;
    } else {
      steps.push(u.bi(
        u.human(nominal) + ' is a ' + u.weekdayName(nominal) + ' and the ' + cal.officeName(office) + ' is open, so the date stands.',
        u.humanJa(nominal) + 'は' + u.weekdayNameJa(nominal) + 'で' + cal.officeNameJa(office) + 'は開庁しているため、この日が期限です。',
      ));
    }
  }

  let finalDate = '';
  if (rule.kind === 'extendable' || rule.kind === 'designated') {
    let finalNominal = '';
    if (rule.final_offset_months > 0) finalNominal = u.addYMD(base, extraYears, rule.final_offset_months, 0);
    else if (rule.final_offset_days > 0) {
      finalNominal = rule.business ? cal.addBusinessDays(app, office, base, rule.final_offset_days).date : u.addDays(base, rule.final_offset_days);
    } else if (rule.extensions.length > 0) {
      const last = rule.extensions[rule.extensions.length - 1];
      if (Number(last.days) > 0) finalNominal = rule.business ? cal.addBusinessDays(app, office, nominal, Number(last.days)).date : u.addDays(nominal, Number(last.days));
      else finalNominal = u.addYMD(nominal, 0, Number(last.months) || 0, 0);
    }
    if (finalNominal !== '') {
      finalDate = office !== '' && !rule.business ? cal.rollForward(app, office, finalNominal).date : finalNominal;
      const labels = rule.extensions.map(function (x) {
        return x.label;
      });
      const labelsJa = rule.extensions.map(function (x) {
        return x.label_ja || x.label;
      });
      steps.push(u.bi(
        'Extendable to ' + u.human(finalDate) + (labels.length ? ' (' + labels.join('; ') + ').' : '.'),
        u.humanJa(finalDate) + 'まで延長可能' + (labelsJa.length ? '（' + labelsJa.join('、') + '）。' : '。'),
      ));
    }
  } else if (rule.final_offset_days > 0) {
    finalDate = rule.business ? cal.addBusinessDays(app, office, base, rule.final_offset_days).date : u.addDays(base, rule.final_offset_days);
  }
  if (finalDate !== '' && rule.kind === 'hard' && rule.final_offset_days > 0) {
    steps.push(u.bi('The window closes on ' + u.human(finalDate) + '.', '期間の最終日：' + u.humanJa(finalDate) + '。'));
  }

  // Window and grace run from the statutory (nominal) date, not the rolled one:
  // rolling first would push the grace end past the real last day.
  const windowOpens = rule.window_months > 0 ? u.addYMD(nominal, 0, -rule.window_months, 0) : '';
  if (windowOpens !== '') steps.push(u.bi('Can be filed or paid from ' + u.human(windowOpens) + '.', u.humanJa(windowOpens) + 'から手続・納付が可能。'));

  let graceEnd = '';
  if (rule.grace_months > 0) {
    const g = u.addYMD(nominal, 0, rule.grace_months, 0);
    graceEnd = office !== '' ? cal.rollForward(app, office, g).date : g;
    steps.push(u.bi(
      'Grace period ends ' + u.human(graceEnd) + '.' + (rule.grace_note ? ' ' + rule.grace_note : ''),
      '猶予期間の満了：' + u.humanJa(graceEnd) + '。',
    ));
  }

  let target = due;
  const buffer = Number(bufferDays) > 0 ? Number(bufferDays) : 0;
  if (STATUTORY[rule.kind] && buffer > 0 && !rule.business) {
    target = u.addDays(due, -buffer);
    if (windowOpens !== '' && target < windowOpens) target = windowOpens;
    if (target < base) target = base;
    steps.push(u.bi(
      'Target date set ' + buffer + ' days before the due date (organization setting).',
      '社内目標日は期限の' + buffer + '日前（組織設定）。',
    ));
  }

  return {
    base_date: base,
    base_label: baseInfo.label,
    nominal: nominal,
    due: due,
    target: target,
    final: finalDate,
    window_opens: windowOpens,
    grace_end: graceEnd,
    steps: steps,
    office: office,
  };
}

/* ------------------------------------------------------------------ */
/* Proposals (preview) and commit                                      */
/* ------------------------------------------------------------------ */

function deadlineKey(rule, subject, cycle, baseDate) {
  return 'rule:' + rule.code + ':' + subject.type + ':' + subject.id + ':' + (rule.every > 0 ? 'c' + cycle : baseDate);
}

function existingKeys(app, subject) {
  const u = require(`${__hooks}/lib_util.js`);
  const map = {};
  const rows = u.findMany(app, 'deadlines', SUBJECTS[subject.type].field + ' = {:id}', '', 0, { id: subject.id });
  for (const r of rows) {
    const k = r.getString('key');
    if (k) map[k] = r.getString('status');
  }
  return map;
}

function expiryOf(app, subject) {
  const u = require(`${__hooks}/lib_util.js`);
  if (subject.type !== 'matter') return '';
  return u.d10(subject.record.getString('expiry_date'));
}

/**
 * Deadlines a new event would create. Nothing is written.
 * event: { code, date, data }
 */
function proposalsFor(app, subject, event, opts) {
  const u = require(`${__hooks}/lib_util.js`);
  const o = opts || {};
  const eventDate = u.d10(event.date);
  const data = event.data || {};
  const buffer = Number(u.setting(app, 'target_buffer_days', 14)) || 0;
  const todayD = u.today();
  const rules = candidateRules(app, event.code);
  const events = subjectEvents(app, subject);
  const keys = existingKeys(app, subject);
  const expiry = expiryOf(app, subject);
  const out = [];
  for (const rule of rules) {
    if (!ruleMatches(app, rule, subject, eventDate, events, data)) continue;
    if (Array.isArray(o.onlyCodes) && o.onlyCodes.length && o.onlyCodes.indexOf(rule.code) < 0) continue;
    const overrides = (data.overrides && data.overrides[rule.code]) || data;
    let cycle = rule.every > 0 ? rule.first : Number((rule.conditions && rule.conditions.cycle) || 0);
    let calc = null;
    if (rule.every > 0) {
      let found = false;
      const baseStart = resolveBase(rule, subject, eventDate).date;
      const limit = rule.until > 0 && baseStart !== '' ? u.addYMD(baseStart, rule.until, 0, 0) : '';
      for (let n = rule.first; n < rule.first + 200; n++) {
        const c = computeRule(app, rule, subject, eventDate, n, overrides, buffer, data);
        if (c === null) break;
        if (limit !== '' && c.due > limit) break;
        if (rule.conditions && rule.conditions.stop_at_expiry && expiry !== '' && c.due > expiry) break;
        const stillOpen = (c.grace_end || c.due) >= todayD;
        if (c.due >= eventDate && stillOpen) {
          cycle = n;
          calc = c;
          found = true;
          break;
        }
      }
      if (!found) continue;
    } else {
      calc = computeRule(app, rule, subject, eventDate, cycle, overrides, buffer, data);
      if (calc === null) continue;
    }
    const key = deadlineKey(rule, subject, cycle, calc.base_date);
    const past = (calc.final || calc.grace_end || calc.due) < todayD;
    const exists = Object.prototype.hasOwnProperty.call(keys, key);
    const title = cycleTitle(rule, cycle);
    out.push({
      rule_id: rule.id,
      rule_code: rule.code,
      rule_name: rule.name,
      rule_name_ja: rule.name_ja,
      title: title.en,
      title_ja: title.ja,
      cycle_label: cycleLabel(rule, cycle),
      kind: rule.kind,
      category: rule.category,
      cycle: cycle,
      base_date: calc.base_date,
      nominal_date: calc.nominal,
      due_date: calc.due,
      target_date: calc.target,
      final_date: calc.final,
      window_opens: calc.window_opens,
      grace_end: calc.grace_end,
      office: calc.office,
      citation: rule.citation,
      notes: rule.notes,
      steps: calc.steps,
      key: key,
      past: past,
      exists: exists,
      selected: !past && !exists,
      creates_renewal: rule.creates_renewal,
      fee_kind: rule.fee_kind,
      extensions: rule.extensions,
      business: rule.business,
      overrides: overrides,
    });
  }
  out.sort(function (a, b) {
    return a.due_date < b.due_date ? -1 : a.due_date > b.due_date ? 1 : 0;
  });
  return out;
}

function defaultAssignee(subject) {
  if (!subject || !subject.record) return '';
  const rec = subject.record;
  for (const f of ['responsible', 'docketer', 'assignee']) {
    try {
      const v = rec.getString(f);
      if (v) return v;
    } catch {
      /* field absent */
    }
  }
  if (subject.type === 'talent') {
    try {
      const m = rec.getStringSlice('managers') || [];
      if (m.length) return String(m[0]);
    } catch {
      /* none */
    }
  }
  return '';
}

function denorm(subject) {
  const rec = subject.record;
  const out = {
    jurisdiction: subject.jurisdiction === '*' ? '' : subject.jurisdiction,
    subject_type: subject.subject_type,
    ref: '',
    subject_label: subject.label,
    family: '',
  };
  try {
    out.ref = rec.getString('ref') || '';
  } catch {
    out.ref = '';
  }
  if (subject.type === 'matter') out.family = rec.getString('family');
  return out;
}

/** Create deadline records for selected proposals. Returns created records. */
function commit(app, subject, eventRec, proposals, actorId, source) {
  const u = require(`${__hooks}/lib_util.js`);
  const created = [];
  const keys = existingKeys(app, subject);
  const dn = denorm(subject);
  for (const p of proposals) {
    if (p.selected === false) continue;
    if (Object.prototype.hasOwnProperty.call(keys, p.key)) continue;
    const data = {
      title: p.title,
      title_ja: p.title_ja || p.title,
      kind: p.kind,
      category: p.category,
      status: 'open',
      target_date: u.toPb(p.target_date),
      due_date: u.toPb(p.due_date),
      final_date: u.toPb(p.final_date),
      window_opens: u.toPb(p.window_opens),
      grace_end: u.toPb(p.grace_end),
      nominal_date: u.toPb(p.nominal_date),
      base_date: u.toPb(p.base_date),
      source: source || (p.category === 'playbook' ? 'playbook' : 'rule'),
      rule: p.rule_id || '',
      rule_code: p.rule_code || '',
      base_event: eventRec ? eventRec.id : '',
      calculation: {
        steps: p.steps,
        rule_code: p.rule_code,
        base_date: p.base_date,
        nominal: p.nominal_date,
        office: p.office || '',
        business: p.business === true,
        overrides: p.overrides || {},
        computed_at: u.nowIso(),
      },
      locked: false,
      extension_level: 0,
      cycle: p.cycle || 0,
      key: p.key,
      citation: p.citation || '',
      notes: p.notes || '',
      assignee: p.assignee || defaultAssignee(subject),
      jurisdiction: dn.jurisdiction,
      subject_type: dn.subject_type,
      ref: dn.ref,
      subject_label: dn.subject_label,
      family: dn.family,
      reminders_sent: [],
    };
    data[SUBJECTS[subject.type].field] = subject.id;
    const rec = u.newRecord(app, 'deadlines', data);
    app.save(rec);
    keys[p.key] = 'open';
    created.push(rec);
    if (p.creates_renewal) ensureRenewal(app, rec);
  }
  if (created.length) {
    u.audit(
      app,
      actorId,
      'generate',
      'deadlines',
      subject.id,
      subject.label,
      {
        created: created.map(function (r) {
          return { id: r.id, title: r.getString('title'), due: r.getString('due_date').slice(0, 10) };
        }),
      },
      eventRec ? 'From event ' + eventRec.getString('code') + ' on ' + eventRec.getString('date').slice(0, 10) : '',
    );
  }
  return created;
}

/** Apply an event's status/date effect to its subject. */
function applyEventToSubject(app, subject, code, date) {
  const u = require(`${__hooks}/lib_util.js`);
  const def = EVENT_CODES[code];
  if (!def) return false;
  const rec = subject.record;
  let changed = false;
  if (subject.type === 'matter') {
    if (def.field && u.d10(rec.getString(def.field)) === '' && u.d10(date) !== '') {
      rec.set(def.field, u.toPb(date));
      changed = true;
    }
    if (def.status) {
      const cur = rec.getString('status');
      // Never resurrect a dead matter from a stale event, never regress a live one.
      const curGroup = statusGroup(cur);
      const nextGroup = statusGroup(def.status);
      const regress = curGroup === 'live' && nextGroup === 'pending';
      if (cur !== def.status && !(curGroup === 'dead' && nextGroup !== 'dead') && !regress) {
        rec.set('status', def.status);
        rec.set('status_date', u.toPb(date));
        changed = true;
      }
    }
  } else if (subject.type === 'talent' && def.status) {
    if (rec.getString('lifecycle') !== def.status) {
      rec.set('lifecycle', def.status);
      changed = true;
    }
    if (code === 'GRADUATED' && u.d10(rec.getString('graduation_date')) === '') {
      rec.set('graduation_date', u.toPb(date));
      changed = true;
    }
    if (code === 'DEBUTED' && u.d10(rec.getString('debut_date')) === '') {
      rec.set('debut_date', u.toPb(date));
      changed = true;
    }
  } else if ((subject.type === 'claim' || subject.type === 'case' || subject.type === 'recordation') && def.status) {
    if (rec.getString('status') !== def.status) {
      rec.set('status', def.status);
      changed = true;
    }
    if (subject.type === 'claim' && code === 'CID_DISPUTE_RECEIVED' && u.d10(rec.getString('dispute_received')) === '') rec.set('dispute_received', u.toPb(date));
    if (subject.type === 'claim' && code === 'CID_APPEAL_RECEIVED' && u.d10(rec.getString('appeal_received')) === '') rec.set('appeal_received', u.toPb(date));
    if (subject.type === 'case' && code === 'PLATFORM_REQUEST_SENT' && u.d10(rec.getString('request_sent')) === '') rec.set('request_sent', u.toPb(date));
    if (subject.type === 'case' && code === 'COUNTER_NOTICE_RECEIVED' && u.d10(rec.getString('counter_notice_date')) === '') rec.set('counter_notice_date', u.toPb(date));
    if (subject.type === 'recordation' && code === 'RECORDATION_ACCEPTED' && u.d10(rec.getString('accepted_date')) === '') rec.set('accepted_date', u.toPb(date));
  }
  if (changed) app.save(rec);
  return changed;
}

/**
 * Record an event and (optionally) create its deadlines.
 * opts: { data, label, source, actorId, documentId, commit: bool, select: [keys], skip: [keys] }
 */
function recordEvent(app, subject, code, date, opts) {
  const u = require(`${__hooks}/lib_util.js`);
  const o = opts || {};
  const lbl = eventLabel(code);
  const eventData = {
    code: code,
    label: o.label || lbl.en,
    label_ja: o.label_ja || o.label || lbl.ja,
    date: u.toPb(date),
    source: o.source || 'manual',
    document: o.documentId || '',
    data: o.data || {},
    created_by: o.actorId || '',
  };
  eventData[SUBJECTS[subject.type].field] = subject.id;
  const ev = u.newRecord(app, 'events', eventData);
  app.save(ev);
  if (applyEventToSubject(app, subject, code, date)) {
    subject.record = u.byId(app, SUBJECTS[subject.type].coll, subject.id) || subject.record;
  }
  const proposals = proposalsFor(app, subject, { code: code, date: date, data: o.data || {} });
  if (Array.isArray(o.select)) {
    for (const p of proposals) p.selected = o.select.indexOf(p.key) >= 0 || o.select.indexOf(p.rule_code) >= 0;
  }
  if (Array.isArray(o.skip)) {
    for (const p of proposals) if (o.skip.indexOf(p.key) >= 0 || o.skip.indexOf(p.rule_code) >= 0) p.selected = false;
  }
  if (Array.isArray(o.assignees)) {
    for (const p of proposals) {
      for (const a of o.assignees) if (a && (a.key === p.key || a.rule_code === p.rule_code)) p.assignee = a.assignee || '';
    }
  }
  let created = [];
  if (o.commit !== false) created = commit(app, subject, ev, proposals, o.actorId, o.deadlineSource);
  u.audit(app, o.actorId, 'event', 'events', ev.id, subject.label + ': ' + eventData.label, { code: code, date: u.d10(date) }, '');
  if (subject.type === 'matter') refreshMatterSummary(app, subject.id);
  return { event: ev, proposals: proposals, created: created };
}

/** Make sure a system event exists for (subject, code) at `date`; move it and regenerate if the date changed. */
function ensureSystemEvent(app, subject, code, date, actorId, data) {
  const u = require(`${__hooks}/lib_util.js`);
  if (u.d10(date) === '') return { created: 0, moved: 0 };
  const evs = u.findMany(app, 'events', SUBJECTS[subject.type].field + ' = {:id} && code = {:c}', '-created', 0, { id: subject.id, c: code });
  if (evs.length === 0) {
    const r = recordEvent(app, subject, code, date, { source: 'system', actorId: actorId, data: data || {} });
    return { created: r.created.length, moved: 0 };
  }
  if (u.d10(evs[0].getString('date')) !== u.d10(date)) {
    evs[0].set('date', u.toPb(date));
    app.save(evs[0]);
    const r = regenerate(app, subject, true, actorId);
    return { created: 0, moved: r.moved.length };
  }
  return { created: 0, moved: 0 };
}

/* ------------------------------------------------------------------ */
/* Regeneration (diff before apply)                                    */
/* ------------------------------------------------------------------ */

function regenerate(app, subject, apply, actorId) {
  const u = require(`${__hooks}/lib_util.js`);
  const cal = require(`${__hooks}/lib_calendar.js`);
  const buffer = Number(u.setting(app, 'target_buffer_days', 14)) || 0;
  const rows = u.findMany(
    app,
    'deadlines',
    SUBJECTS[subject.type].field + ' = {:id} && status = "open" && (source = "rule" || source = "playbook")',
    'due_date',
    0,
    { id: subject.id },
  );
  const diffs = [];
  for (const dl of rows) {
    if (dl.getBool('locked')) continue;
    const ruleId = dl.getString('rule');
    if (!ruleId) continue;
    const rr = u.byId(app, 'rules', ruleId);
    if (rr === null) continue;
    const rule = ruleObj(rr);
    const calcPrev = u.j(dl, 'calculation', {});
    const ev = dl.getString('base_event') ? u.byId(app, 'events', dl.getString('base_event')) : null;
    const eventDate = ev ? u.d10(ev.getString('date')) : u.d10(dl.getString('base_date'));
    const evData = ev ? u.j(ev, 'data', {}) : {};
    const c = computeRule(app, rule, subject, eventDate, dl.getInt('cycle') || rule.first, calcPrev.overrides || {}, buffer, evData);
    if (c === null) continue;
    let due = c.due;
    const finalD = c.final;
    const level = dl.getInt('extension_level');
    if (level > 0 && rule.extensions[level - 1]) {
      const ext = rule.extensions[level - 1];
      if (Number(ext.days) > 0) due = rule.business ? cal.addBusinessDays(app, c.office, c.nominal, Number(ext.days)).date : u.addDays(c.nominal, Number(ext.days));
      else {
        const nominal = u.addYMD(c.nominal, 0, Number(ext.months) || 0, 0);
        due = c.office ? cal.rollForward(app, c.office, nominal).date : nominal;
      }
    }
    const oldDue = u.d10(dl.getString('due_date'));
    if (due !== oldDue || finalD !== u.d10(dl.getString('final_date'))) {
      diffs.push({
        id: dl.id,
        title: dl.getString('title'),
        title_ja: dl.getString('title_ja'),
        from: oldDue,
        to: due,
        final_from: u.d10(dl.getString('final_date')),
        final_to: finalD,
      });
      if (apply) {
        dl.set('due_date', u.toPb(due));
        dl.set('target_date', u.toPb(level > 0 ? u.addDays(due, -buffer) : c.target));
        dl.set('final_date', u.toPb(finalD));
        dl.set('window_opens', u.toPb(c.window_opens));
        dl.set('grace_end', u.toPb(c.grace_end));
        dl.set('nominal_date', u.toPb(c.nominal));
        dl.set('base_date', u.toPb(c.base_date));
        const steps = c.steps.slice();
        steps.push(u.bi(
          'Recalculated on ' + u.human(u.today()) + ' after the base data changed (was ' + u.human(oldDue) + ').',
          u.humanJa(u.today()) + 'に基礎データの変更により再計算（変更前 ' + u.humanJa(oldDue) + '）。',
        ));
        dl.set('calculation', {
          steps: steps,
          rule_code: rule.code,
          base_date: c.base_date,
          nominal: c.nominal,
          office: c.office,
          business: rule.business,
          overrides: calcPrev.overrides || {},
          computed_at: u.nowIso(),
        });
        app.save(dl);
      }
    }
  }
  if (apply && diffs.length) {
    u.audit(app, actorId, 'regenerate', 'deadlines', subject.id, subject.label, { moved: diffs }, 'Base data changed');
    if (subject.type === 'matter') refreshMatterSummary(app, subject.id);
  }
  return { moved: diffs, unchanged: rows.length - diffs.length };
}

/* ------------------------------------------------------------------ */
/* Close, extend, next cycle                                           */
/* ------------------------------------------------------------------ */

const NEEDS_REASON = { not_needed: true, cancelled: true, transferred: true, missed: true };
const CLOSE_STATUSES = { done: true, not_needed: true, missed: true, transferred: true, cancelled: true, extended: true };
const CLOSE_LABEL_JA = { done: '完了', not_needed: '不要', missed: '期限徒過', transferred: '移管', cancelled: '取消', extended: '延長' };

function subjectOfDeadline(app, dl) {
  for (const type of Object.keys(SUBJECTS)) {
    const id = dl.getString(SUBJECTS[type].field);
    if (id) return subjectOf(app, type, id);
  }
  return null;
}

function closeDeadline(app, dl, status, reason, actorId, closedOn) {
  const u = require(`${__hooks}/lib_util.js`);
  if (dl.getString('status') !== 'open') {
    throw u.err('"' + dl.getString('title') + '" is already closed.', '「' + (dl.getString('title_ja') || dl.getString('title')) + '」はすでに完了しています。');
  }
  if (!CLOSE_STATUSES[status]) throw u.err('Unknown close status: ' + status, '不明な完了ステータス：' + status);
  if (NEEDS_REASON[status] && String(reason || '').trim() === '') {
    throw u.err('A reason is required to close as "' + status.replace('_', ' ') + '".', '「' + CLOSE_LABEL_JA[status] + '」で閉じるには理由が必要です。');
  }
  dl.set('status', status);
  dl.set('close_reason', String(reason || '').slice(0, 2000));
  dl.set('closed_at', u.toPb(closedOn || u.today()));
  dl.set('closed_by', actorId || '');
  app.save(dl);
  u.audit(app, actorId, 'close', 'deadlines', dl.id, (dl.getString('ref') ? dl.getString('ref') + ': ' : '') + dl.getString('title'), { status: status }, reason || '');
  let next = null;
  if (status === 'done') next = nextCycle(app, dl, actorId);
  const r = u.findOne(app, 'renewals', 'deadline = {:d}', { d: dl.id });
  if (r !== null) {
    if (status === 'done' && r.getString('instruction_status') !== 'confirmed') {
      r.set('instruction_status', 'confirmed');
      if (r.getString('decision') === 'pending') r.set('decision', 'renew');
      app.save(r);
    }
    if ((status === 'not_needed' || status === 'missed') && r.getString('decision') === 'pending') {
      r.set('decision', 'lapse');
      r.set('rationale', reason || '');
      app.save(r);
    }
  }
  const mid = dl.getString('matter');
  if (mid) refreshMatterSummary(app, mid);
  return { deadline: dl, next: next };
}

function nextCycle(app, dl, actorId) {
  const u = require(`${__hooks}/lib_util.js`);
  const ruleId = dl.getString('rule');
  if (!ruleId) return null;
  const rr = u.byId(app, 'rules', ruleId);
  if (rr === null) return null;
  const rule = ruleObj(rr);
  if (!(rule.every > 0)) return null;
  const subject = subjectOfDeadline(app, dl);
  if (subject === null) return null;
  if (subject.type === 'matter' && statusGroup(subject.record.getString('status')) === 'dead') return null;
  const buffer = Number(u.setting(app, 'target_buffer_days', 14)) || 0;
  const ev = dl.getString('base_event') ? u.byId(app, 'events', dl.getString('base_event')) : null;
  const eventDate = ev ? u.d10(ev.getString('date')) : u.d10(dl.getString('base_date'));
  const n = (dl.getInt('cycle') || rule.first) + 1;
  const c = computeRule(app, rule, subject, eventDate, n, {}, buffer, ev ? u.j(ev, 'data', {}) : {});
  if (c === null) return null;
  if (rule.until > 0 && c.due > u.addYMD(c.base_date, rule.until, 0, 0)) return null;
  if (rule.conditions && rule.conditions.stop_at_expiry && subject.type === 'matter') {
    refreshMatterSummary(app, subject.id);
    const fresh = u.byId(app, 'matters', subject.id);
    const exp = fresh ? u.d10(fresh.getString('expiry_date')) : '';
    if (exp !== '' && c.due > exp) return null;
  }
  if (rule.conditions && rule.conditions.stop_on_event) {
    const evs = subjectEvents(app, subject);
    for (const x of evs) if (x.getString('code') === rule.conditions.stop_on_event) return null;
  }
  const title = cycleTitle(rule, n);
  const proposal = {
    rule_id: rule.id,
    rule_code: rule.code,
    title: title.en,
    title_ja: title.ja,
    kind: rule.kind,
    category: rule.category,
    cycle: n,
    base_date: c.base_date,
    nominal_date: c.nominal,
    due_date: c.due,
    target_date: c.target,
    final_date: c.final,
    window_opens: c.window_opens,
    grace_end: c.grace_end,
    office: c.office,
    citation: rule.citation,
    notes: rule.notes,
    steps: c.steps,
    key: deadlineKey(rule, subject, n, c.base_date),
    selected: true,
    creates_renewal: rule.creates_renewal,
    business: rule.business,
    assignee: dl.getString('assignee'),
  };
  const created = commit(app, subject, ev, [proposal], actorId);
  return created.length ? created[0] : null;
}

/** Extend to a tier. preview=true returns the new dates without saving. */
function extendDeadline(app, dl, level, actorId, preview) {
  const u = require(`${__hooks}/lib_util.js`);
  const cal = require(`${__hooks}/lib_calendar.js`);
  const ruleId = dl.getString('rule');
  const rr = ruleId ? u.byId(app, 'rules', ruleId) : null;
  const rule = rr ? ruleObj(rr) : null;
  const calc = u.j(dl, 'calculation', {});
  const exts = rule ? rule.extensions : calc.extensions || [];
  if (!exts || !exts.length) throw u.err('This deadline has no extension options.', 'この期限には延長の選択肢がありません。');
  const lvl = Number(level);
  if (!(lvl >= 1 && lvl <= exts.length)) {
    throw u.err('Choose an extension between 1 and ' + exts.length + '.', '1から' + exts.length + 'の延長段階を選んでください。');
  }
  if (lvl <= dl.getInt('extension_level')) throw u.err('This deadline is already extended to that tier.', 'この期限はすでにその段階まで延長されています。');
  const ext = exts[lvl - 1];
  const nominalBase = u.d10(calc.nominal) || u.d10(dl.getString('nominal_date')) || u.d10(dl.getString('due_date'));
  const office = calc.office || dl.getString('jurisdiction') || '';
  let rolled;
  if (Number(ext.days) > 0) {
    rolled = calc.business ? cal.addBusinessDays(app, office, nominalBase, Number(ext.days)) : { date: u.addDays(nominalBase, Number(ext.days)), steps: [] };
  } else {
    const nominal = u.addYMD(nominalBase, 0, Number(ext.months) || 0, 0);
    rolled = office ? cal.rollForward(app, office, nominal) : { date: nominal, steps: [] };
  }
  const newDue = rolled.date;
  const finalD = u.d10(dl.getString('final_date'));
  if (finalD !== '' && newDue > finalD) {
    throw u.err('That extension goes past the final date (' + u.human(finalD) + ').', 'その延長は最終期限（' + u.humanJa(finalD) + '）を超えます。');
  }
  const buffer = Number(u.setting(app, 'target_buffer_days', 14)) || 0;
  const result = {
    id: dl.id,
    title: dl.getString('title'),
    from: u.d10(dl.getString('due_date')),
    to: newDue,
    label: ext.label || ext.months + '-month extension',
    label_ja: ext.label_ja || ext.label || ext.months + 'か月延長',
    steps: rolled.steps,
  };
  if (preview) return result;
  const steps = (calc.steps || []).slice();
  steps.push(u.bi(
    'Extended on ' + u.human(u.today()) + ' by ' + u.userLabel(app, actorId) + ': ' + result.label + '. New due date ' + u.human(newDue) + '.',
    u.humanJa(u.today()) + 'に' + u.userLabel(app, actorId) + 'が延長：' + result.label_ja + '。新しい期限 ' + u.humanJa(newDue) + '。',
  ));
  for (const s of rolled.steps) steps.push(s);
  calc.steps = steps;
  dl.set('calculation', calc);
  dl.set('due_date', u.toPb(newDue));
  dl.set('target_date', u.toPb(calc.business ? newDue : u.addDays(newDue, -buffer)));
  dl.set('extension_level', lvl);
  app.save(dl);
  u.audit(app, actorId, 'extend', 'deadlines', dl.id, dl.getString('title'), { from: result.from, to: newDue, tier: lvl }, result.label);
  const mid = dl.getString('matter');
  if (mid) refreshMatterSummary(app, mid);
  return result;
}

/* ------------------------------------------------------------------ */
/* Matter summary, expiry                                              */
/* ------------------------------------------------------------------ */

function renewalCount(app, matterId) {
  const u = require(`${__hooks}/lib_util.js`);
  return u.findMany(app, 'events', 'matter = {:m} && code = "RENEWED"', '', 0, { m: matterId }).length;
}

/** Statutory expiry for a trademark or design: { date, text: { en, ja } }. */
function computeExpiry(app, matter) {
  const u = require(`${__hooks}/lib_util.js`);
  const t = matter.getString('ip_type');
  const cc = matter.getString('jurisdiction').toUpperCase();
  const filing = u.d10(matter.getString('filing_date'));
  const reg = u.d10(matter.getString('registration_date'));
  if (t === 'design') {
    if (cc === 'US') {
      if (reg === '') return { date: '', text: u.bi('US design term runs 15 years from grant.', '米国の意匠は登録から15年です。') };
      return { date: u.addYMD(reg, 15, 0, 0), text: u.bi('15 years from grant (35 U.S.C. 173).', '登録から15年（35 U.S.C. 173）。') };
    }
    if (filing === '') return { date: '', text: u.bi('Needs a filing date.', '出願日が必要です。') };
    const years = { JP: 25, EM: 25, CN: 15, KR: 20, TW: 15 }[cc] || 25;
    const cite = {
      JP: 'JP Design Act Art. 21(1)',
      EM: 'Reg. (EC) 6/2002 Art. 12',
      CN: 'CN Patent Law Art. 42 (designs filed from 1 June 2021)',
      KR: 'KR Design Protection Act Art. 91',
      TW: 'TW Patent Act Art. 135',
    }[cc] || 'national law';
    return {
      date: u.addYMD(filing, years, 0, 0),
      text: u.bi(
        'Maximum ' + years + ' years from filing, subject to renewals or annual fees (' + cite + ').',
        '出願から最長' + years + '年（更新・年金の納付が条件、' + cite + '）。',
      ),
    };
  }
  if (t === 'trademark') {
    const k = renewalCount(app, matter.id) + 1;
    const renewed = k > 1 ? ' (' + (k - 1) + ' renewal(s) recorded).' : '.';
    const renewedJa = k > 1 ? '（更新' + (k - 1) + '回記録済み）。' : '。';
    if (cc === 'EM') {
      if (filing === '') return { date: '', text: u.bi('EU trade marks run 10 years from filing.', 'EU商標は出願から10年です。') };
      return {
        date: u.addYMD(filing, 10 * k, 0, 0),
        text: u.bi('10 years from filing, renewable every 10 years' + renewed, '出願から10年、10年ごとに更新可能' + renewedJa),
      };
    }
    if (reg === '') return { date: '', text: u.bi('The term starts at registration.', '存続期間は登録日から始まります。') };
    return {
      date: u.addYMD(reg, 10 * k, 0, 0),
      text: u.bi('10 years from registration, renewable every 10 years' + renewed, '登録から10年、10年ごとに更新可能' + renewedJa),
    };
  }
  return { date: '', text: u.bi('', '') };
}

const FILM_TYPES = ['series', 'season', 'episode', 'film', 'ova', 'special', 'short', 'stream', 'stream_archive', 'music_video'];

/** Copyright term under US, Japanese and EU law for a title: { US, JP, EU } each { date, text: { en, ja }, flags }. */
function copyrightTerms(work) {
  const u = require(`${__hooks}/lib_util.js`);
  const pub = u.d10(work.getString('publication_date'));
  const created = u.d10(work.getString('creation_date'));
  const death = work.getInt('author_death_year');
  const tt = work.getString('title_type');
  const film = FILM_TYPES.indexOf(tt) >= 0 || work.getString('author_kind') === 'film';
  const kind = work.getString('author_kind') || (work.getBool('made_for_hire') ? 'corporate' : film ? 'film' : 'individual');
  const out = {};
  function endOfYear(y) {
    return y + '-12-31';
  }
  const flags = [];
  if (pub !== '' && pub < '1971-01-01' && film) {
    flags.push(u.bi(
      'Published before 1971: the old Copyright Act may give a longer term (author death + 38 years). Check case by case.',
      '1971年以前の公表：旧著作権法により保護期間が長くなる場合があります（著作者の死後38年）。個別に確認してください。',
    ));
  }
  // United States (17 U.S.C. 302, 305: terms run to the end of the calendar year).
  if (work.getBool('made_for_hire') || kind === 'corporate' || kind === 'anonymous' || kind === 'film') {
    const a = pub ? Number(pub.slice(0, 4)) + 95 : 0;
    const b = created ? Number(created.slice(0, 4)) + 120 : 0;
    const y = a && b ? Math.min(a, b) : a || b;
    out.US = y
      ? {
          date: endOfYear(y),
          text: u.bi(
            '95 years from publication or 120 years from creation, whichever ends first, if a work made for hire (17 U.S.C. 302(c)). Whether a Japanese title is a US work made for hire depends on the facts.',
            '職務著作の場合、発行から95年または創作から120年の早い方（17 U.S.C. 302(c)）。日本の作品が米国の職務著作に当たるかは事実関係によります。',
          ),
        }
      : { date: '', text: u.bi('Needs a publication or creation date.', '公表日または創作日が必要です。') };
  } else if (death > 0) {
    out.US = {
      date: endOfYear(death + 70),
      text: u.bi(
        'Life of the ' + (kind === 'joint' ? 'last surviving author' : 'author') + ' plus 70 years (17 U.S.C. 302(a), (b)).',
        (kind === 'joint' ? '最後に死亡した著作者' : '著作者') + 'の死後70年（17 U.S.C. 302(a), (b)）。',
      ),
    };
  } else {
    out.US = { date: '', text: u.bi('Life of the author plus 70 years. Enter the author death year when known.', '著作者の死後70年。判明したら死亡年を入力してください。') };
  }
  // Japan (Copyright Act Art. 51-54, 56, 57: counted from 1 January of the following year).
  if (film) {
    out.JP = pub
      ? {
          date: endOfYear(Number(pub.slice(0, 4)) + 70),
          text: u.bi(
            'Cinematographic works: 70 years from publication (Art. 54(1)). Episodes released in instalments are timed one by one (Art. 56). When the film\'s term ends, the original work\'s copyright for use in that film ends too (Art. 54(2)).',
            '映画の著作物：公表後70年（54条1項）。回を追って公表される作品は各回ごとに計算（56条）。映画の保護期間が終わると、その映画の利用に関する原作の著作権も消滅（54条2項）。',
          ),
          flags: flags,
        }
      : { date: '', text: u.bi('Cinematographic works: 70 years from publication (Art. 54).', '映画の著作物：公表後70年（54条）。'), flags: flags };
  } else if (kind === 'corporate' || work.getBool('made_for_hire') || kind === 'anonymous') {
    const y = pub ? Number(pub.slice(0, 4)) : created ? Number(created.slice(0, 4)) : 0;
    out.JP = y
      ? {
          date: endOfYear(y + 70),
          text: u.bi('Works under a corporate or anonymous name: 70 years from publication (Art. 52, 53).', '団体名義・無名の著作物：公表後70年（52条、53条）。'),
          flags: flags,
        }
      : { date: '', text: u.bi('Needs a publication date.', '公表日が必要です。'), flags: flags };
  } else if (death > 0) {
    out.JP = { date: endOfYear(death + 70), text: u.bi('Life of the author plus 70 years (Art. 51, 57).', '著作者の死後70年（51条、57条）。'), flags: flags };
  } else {
    out.JP = {
      date: '',
      text: u.bi('Life of the author plus 70 years. Enter the author death year when known.', '著作者の死後70年。判明したら死亡年を入力してください。'),
      flags: flags,
    };
  }
  // European Union (Directive 2006/116/EC).
  if (death > 0 && kind !== 'anonymous') {
    out.EU = {
      date: endOfYear(death + 70),
      text: film
        ? u.bi(
            '70 years after the death of the last of the principal director, screenwriter, dialogue author and composer (Art. 2(2)). Enter the latest death year. Non-EU works never exceed the country-of-origin term (Art. 7(1)).',
            '主たる監督、脚本家、台詞作者、作曲家のうち最後に死亡した者の死後70年（2条2項）。最も遅い死亡年を入力してください。EU域外の作品は本国の保護期間を超えません（7条1項）。',
          )
        : u.bi('Life of the author plus 70 years (Art. 1).', '著作者の死後70年（1条）。'),
    };
  } else if (pub && (kind === 'anonymous' || kind === 'corporate' || work.getBool('made_for_hire'))) {
    out.EU = {
      date: endOfYear(Number(pub.slice(0, 4)) + 70),
      text: u.bi('Anonymous or pseudonymous works: 70 years from lawful publication (Art. 1(3)).', '無名・変名の著作物：適法な公表後70年（1条3項）。'),
    };
  } else {
    out.EU = {
      date: '',
      text: u.bi('Life of the author plus 70 years. Enter the author death year when known.', '著作者の死後70年。判明したら死亡年を入力してください。'),
    };
  }
  return out;
}

function refreshMatterSummary(app, matterId) {
  const u = require(`${__hooks}/lib_util.js`);
  const m = u.byId(app, 'matters', matterId);
  if (m === null) return;
  const open = u.findMany(app, 'deadlines', 'matter = {:m} && status = "open"', 'due_date', 1, { m: matterId });
  const next = open.length ? u.d10(open[0].getString('due_date')) : '';
  const nextTitle = open.length ? open[0].getString('title') : '';
  const nextTitleJa = open.length ? open[0].getString('title_ja') : '';
  let changed = false;
  if (u.d10(m.getString('next_deadline')) !== next) {
    m.set('next_deadline', u.toPb(next));
    changed = true;
  }
  if (m.getString('next_deadline_title') !== nextTitle) {
    m.set('next_deadline_title', nextTitle);
    changed = true;
  }
  if (m.getString('next_deadline_title_ja') !== nextTitleJa) {
    m.set('next_deadline_title_ja', nextTitleJa);
    changed = true;
  }
  if (!m.getBool('expiry_override')) {
    const exp = computeExpiry(app, m).date;
    if (u.d10(m.getString('expiry_date')) !== exp) {
      m.set('expiry_date', u.toPb(exp));
      changed = true;
    }
  }
  if (changed) app.save(m);
}

/* ------------------------------------------------------------------ */
/* Renewals and cost estimates                                         */
/* ------------------------------------------------------------------ */

function classCount(app, matterId) {
  const u = require(`${__hooks}/lib_util.js`);
  return u.findMany(app, 'goods_services', 'matter = {:m} && class_status != "deleted" && class_status != "cancelled"', '', 0, { m: matterId }).length;
}

/** Look up the official fee for a renewal deadline. */
function estimateFee(app, dl, rule, matter) {
  const u = require(`${__hooks}/lib_util.js`);
  const fx = require(`${__hooks}/lib_fx.js`);
  const home = String(u.setting(app, 'home_currency', 'JPY') || 'JPY').toUpperCase();
  const result = { official_fee: 0, currency: '', home_amount: 0, home_currency: home, fee_known: false, fee_note: '' };
  if (matter === null || rule === null || !rule.fee_kind) {
    result.fee_note = 'No fee type on the rule.';
    return result;
  }
  const office = matter.getString('jurisdiction').toUpperCase();
  const ipType = matter.getString('ip_type');
  const cycle = Number((rule.conditions && rule.conditions.cycle) || dl.getInt('cycle') || 0);
  const rows = u.findMany(app, 'fee_schedule', 'office = {:o} && ip_type = {:t} && fee_kind = {:k}', '-effective_from', 0, {
    o: office,
    t: ipType,
    k: rule.fee_kind,
  });
  let best = null;
  let bestScore = -1;
  for (const r of rows) {
    const rc = r.getInt('cycle');
    const rt = r.getInt('cycle_to');
    const inRange = rc === 0 || (rt > 0 ? cycle >= rc && cycle <= rt : cycle === rc);
    if (!inRange) continue;
    // A schedule that only starts after this deadline does not price it.
    const from = u.d10(r.getString('effective_from'));
    const dueDay = u.d10(dl.getString('due_date'));
    if (from !== '' && dueDay !== '' && from > dueDay) continue;
    const score = rc !== 0 ? 2 : 0;
    if (score > bestScore) {
      best = r;
      bestScore = score;
    }
  }
  if (best === null) {
    result.fee_note = 'No ' + office + ' ' + rule.fee_kind.replace('_', ' ') + ' fee on file. Add one in Settings, Fees.';
    return result;
  }
  let amount = best.getFloat('amount');
  const tiers = u
    .asArray(u.j(best, 'class_tiers', []))
    .map(function (t) {
      return { from: Number(t && t.from) || 0, amount: Number(t && t.amount) || 0 };
    })
    .filter(function (t) {
      return t.from > 1;
    })
    .sort(function (a, b) {
      return a.from - b.from;
    });
  const tiered = tiers.length > 0;
  const classes = best.getBool('per_class') || tiered ? Math.max(1, classCount(app, matter.id)) : 1;
  if (tiered) {
    for (let c = 2; c <= classes; c++) {
      let rate = 0;
      for (const t of tiers) if (c >= t.from) rate = t.amount;
      amount += rate;
    }
  } else {
    amount = amount * classes;
  }
  let note = '';
  const graceEnd = u.d10(dl.getString('grace_end'));
  const due = u.d10(dl.getString('due_date'));
  if (graceEnd !== '' && u.today() > due && u.today() <= graceEnd) {
    const s = best.getFloat('grace_surcharge');
    if (s > 0) amount += best.getBool('surcharge_percent') ? amount * (s / 100) : s * (tiered ? 1 : classes);
    note += 'Includes the late payment surcharge. ';
  }
  result.official_fee = u.round2(amount);
  result.currency = best.getString('currency').toUpperCase();
  const conv = fx.convert(app, result.official_fee, result.currency, home);
  result.home_amount = conv === null ? 0 : conv;
  result.fee_known = true;
  result.fee_note =
    (best.getBool('per_class') || tiered ? classes + ' class' + (classes === 1 ? '' : 'es') + '. ' : '') +
    note +
    (best.getString('source') || '') +
    (conv === null && result.currency !== home ? ' No exchange rate for ' + result.currency + ' to ' + home + '.' : '');
  return result;
}

function refreshAllRenewalCosts(app) {
  const u = require(`${__hooks}/lib_util.js`);
  let n = 0;
  for (const r of u.findMany(app, 'renewals', 'instruction_status = "not_instructed"', '', 0)) {
    refreshRenewalCost(app, r);
    n += 1;
  }
  return n;
}

function repriceAfterEdit(app, record) {
  const name = record.collection().name;
  if (name === 'fx_rates' && record.getString('source') !== 'manual') return;
  try {
    refreshAllRenewalCosts(app);
  } catch (error) {
    console.error('renewal re-pricing failed:', error);
  }
}

function ensureRenewal(app, dl) {
  const u = require(`${__hooks}/lib_util.js`);
  const existing = u.findOne(app, 'renewals', 'deadline = {:d}', { d: dl.id });
  if (existing !== null) return existing;
  const mid = dl.getString('matter');
  if (!mid) return null;
  const matter = u.byId(app, 'matters', mid);
  const rr = dl.getString('rule') ? u.byId(app, 'rules', dl.getString('rule')) : null;
  const rule = rr ? ruleObj(rr) : null;
  const est = estimateFee(app, dl, rule, matter);
  const def = String(u.setting(app, 'renewal_default', 'decide'));
  const rec = u.newRecord(app, 'renewals', {
    deadline: dl.id,
    matter: mid,
    cycle_label: rule ? cycleLabel(rule, dl.getInt('cycle')) || dl.getString('title') : dl.getString('title'),
    cycle: dl.getInt('cycle'),
    due_date: dl.getString('due_date'),
    grace_end: dl.getString('grace_end'),
    window_opens: dl.getString('window_opens'),
    official_fee: est.official_fee,
    other_fee: 0,
    currency: est.currency,
    home_amount: est.home_amount,
    home_currency: est.home_currency,
    fee_known: est.fee_known,
    fee_note: est.fee_note,
    decision: def === 'renew' ? 'renew' : def === 'lapse' ? 'lapse' : 'pending',
    instruction_status: 'not_instructed',
    classes_keep: [],
  });
  app.save(rec);
  return rec;
}

function refreshRenewalCost(app, renewal) {
  const u = require(`${__hooks}/lib_util.js`);
  const fx = require(`${__hooks}/lib_fx.js`);
  const dl = u.byId(app, 'deadlines', renewal.getString('deadline'));
  if (dl === null) return renewal;
  const matter = u.byId(app, 'matters', renewal.getString('matter'));
  const rr = dl.getString('rule') ? u.byId(app, 'rules', dl.getString('rule')) : null;
  const est = estimateFee(app, dl, rr ? ruleObj(rr) : null, matter);
  renewal.set('due_date', dl.getString('due_date'));
  renewal.set('grace_end', dl.getString('grace_end'));
  renewal.set('window_opens', dl.getString('window_opens'));
  if (est.fee_known) {
    renewal.set('official_fee', est.official_fee);
    renewal.set('currency', est.currency);
  }
  const cur = renewal.getString('currency');
  const total = renewal.getFloat('official_fee') + renewal.getFloat('other_fee');
  const conv = cur ? fx.convert(app, total, cur, est.home_currency) : null;
  renewal.set('home_amount', conv === null ? 0 : conv);
  renewal.set('home_currency', est.home_currency);
  renewal.set('fee_known', est.fee_known || renewal.getFloat('official_fee') > 0);
  renewal.set('fee_note', est.fee_note);
  app.save(renewal);
  return renewal;
}

/* ------------------------------------------------------------------ */
/* Record-driven events                                                */
/* ------------------------------------------------------------------ */

/** A title with a publication date records WORK_PUBLISHED (US 412 reminder and terms). */
function syncWork(app, work, actorId) {
  const u = require(`${__hooks}/lib_util.js`);
  const pub = u.d10(work.getString('publication_date'));
  if (pub === '') return { created: 0 };
  return ensureSystemEvent(app, subjectFromRecord('work', work), 'WORK_PUBLISHED', pub, actorId);
}

/** Author grants: Section 203 termination windows run from the grant date. */
function syncAuthorGrant(app, agr, actorId) {
  const u = require(`${__hooks}/lib_util.js`);
  if (!agr.getBool('author_grant')) return { created: 0 };
  const signed = u.d10(agr.getString('signed_date'));
  if (signed === '') return { created: 0 };
  return ensureSystemEvent(app, subjectFromRecord('agreement', agr), 'AUTHOR_GRANT_EXECUTED', signed, actorId, { jurisdiction: 'US' });
}

/** Talent dates drive the debut and graduation playbooks. */
function syncTalent(app, talent, actorId) {
  const u = require(`${__hooks}/lib_util.js`);
  const subject = subjectFromRecord('talent', talent);
  const out = { created: 0, moved: 0 };
  const debut = u.d10(talent.getString('debut_date'));
  const life = talent.getString('lifecycle');
  if (debut !== '' && (life === 'audition' || life === 'pre_debut' || life === '') && debut >= u.today()) {
    const r = ensureSystemEvent(app, subject, 'DEBUT_SCHEDULED', u.today() < debut ? u.today() : debut, actorId);
    out.created += r.created;
    if (r.created === 0) {
      const g = regenerate(app, subject, true, actorId);
      out.moved += g.moved.length;
    }
  }
  const grad = u.d10(talent.getString('graduation_date'));
  if (grad !== '' && (life === 'graduation_announced' || life === 'active' || life === 'hiatus')) {
    const evs = u.findMany(app, 'events', 'talent = {:t} && code = "GRADUATION_SCHEDULED"', '', 0, { t: talent.id });
    if (evs.length === 0) {
      const r = recordEvent(app, subject, 'GRADUATION_SCHEDULED', u.today() < grad ? u.today() : grad, { source: 'system', actorId: actorId });
      out.created += r.created.length;
    } else {
      const g = regenerate(app, subject, true, actorId);
      out.moved += g.moved.length;
    }
  }
  return out;
}

/** Customs recordations: the accepted event drives the renewal rule from valid_until. */
function syncRecordation(app, rec, actorId) {
  const u = require(`${__hooks}/lib_util.js`);
  const accepted = u.d10(rec.getString('accepted_date'));
  if (accepted === '' || u.d10(rec.getString('valid_until')) === '') return { created: 0 };
  const subject = subjectFromRecord('recordation', rec);
  const r = ensureSystemEvent(app, subject, 'RECORDATION_ACCEPTED', accepted, actorId, { jurisdiction: rec.getString('jurisdiction') });
  if (r.created === 0) regenerate(app, subject, true, actorId);
  return r;
}

module.exports = {
  SUBJECTS: SUBJECTS,
  EVENT_CODES: EVENT_CODES,
  FILM_TYPES: FILM_TYPES,
  STATUS_GROUP: STATUS_GROUP,
  statusGroup: statusGroup,
  eventLabel: eventLabel,
  subjectOf: subjectOf,
  subjectFromRecord: subjectFromRecord,
  subjectOfDeadline: subjectOfDeadline,
  ruleObj: ruleObj,
  ruleMatches: ruleMatches,
  computeRule: computeRule,
  proposalsFor: proposalsFor,
  commit: commit,
  recordEvent: recordEvent,
  ensureSystemEvent: ensureSystemEvent,
  applyEventToSubject: applyEventToSubject,
  regenerate: regenerate,
  closeDeadline: closeDeadline,
  extendDeadline: extendDeadline,
  nextCycle: nextCycle,
  computeExpiry: computeExpiry,
  copyrightTerms: copyrightTerms,
  refreshMatterSummary: refreshMatterSummary,
  estimateFee: estimateFee,
  ensureRenewal: ensureRenewal,
  refreshRenewalCost: refreshRenewalCost,
  refreshAllRenewalCosts: refreshAllRenewalCosts,
  repriceAfterEdit: repriceAfterEdit,
  syncWork: syncWork,
  syncAuthorGrant: syncAuthorGrant,
  syncTalent: syncTalent,
  syncRecordation: syncRecordation,
  earliestPriority: earliestPriority,
};
