/**
 * Every select field's values and English labels, GENERATED from the schema by
 * reference/tools/gen_records.py. Render labels through enumLabel() so they are translated.
 */

export const ENUM_LABEL: Record<string, Record<string, string>> = {
  'agreements.agreement_type': {
    "original_work_license": "Original work licence",
    "committee": "Production committee",
    "production": "Production",
    "creator_commission": "Creator commission",
    "talent": "Talent agreement",
    "voice_actor": "Voice actor",
    "merchandise": "Merchandise licence",
    "overseas": "Overseas licence",
    "streaming": "Streaming",
    "broadcast": "Broadcast",
    "video": "Video (Blu-ray, DVD)",
    "game": "Game licence",
    "pachinko": "Pachinko and pachislot",
    "stage": "Stage",
    "event_collab": "Event or collaboration",
    "brand_tieup": "Brand tie-up",
    "publishing": "Publishing",
    "music_publishing": "Music publishing",
    "master_license": "Master licence",
    "master_assignment": "Master assignment",
    "co_master": "Co-owned master",
    "tie_up": "Music tie-up",
    "sync": "Sync licence",
    "karaoke": "Karaoke",
    "distribution": "Distribution",
    "platform": "Platform",
    "fan_permit": "Fan permit",
    "assignment": "Assignment",
    "nda": "NDA",
    "settlement": "Settlement",
    "coexistence": "Coexistence",
    "other": "Other",
  },
  'agreements.direction': {
    "in": "In",
    "out": "Out",
    "mutual": "Mutual",
    "none": "None",
  },
  'agreements.status': {
    "draft": "Draft",
    "negotiating": "Negotiating",
    "active": "Active",
    "expired": "Expired",
    "terminated": "Terminated",
    "renewed": "Renewed",
    "superseded": "Superseded",
  },
  'agreements.exclusivity': {
    "exclusive": "Exclusive",
    "non_exclusive": "Non-exclusive",
    "sole": "Sole",
    "mixed": "Mixed",
  },
  'agreements.royalty_basis': {
    "retail_x_manufactured": "Retail price x manufactured",
    "retail_x_sold": "Retail price x sold",
    "wholesale_net": "Net wholesale",
    "net_receipts": "Net receipts",
    "per_unit": "Per unit",
    "per_seal": "Per seal",
    "flat_fee": "Flat fee",
    "revenue_share": "Revenue share",
    "none": "None",
  },
  'agreements.reporting_frequency': {
    "none": "None",
    "monthly": "Monthly",
    "quarterly": "Quarterly",
    "semiannual": "Semiannual",
    "annual": "Annual",
  },
  'agreements.approval_timeout': {
    "none": "None",
    "deemed_refused": "Deemed refused",
    "deemed_approved": "Deemed approved",
  },
  'agreements.stage_name_clause': {
    "agency_owns": "Agency owns the name",
    "talent_owns": "Talent owns the name",
    "shared": "Shared",
    "not_stated": "Not stated",
  },
  'approval_rounds.stage': {
    "proposal": "Proposal",
    "concept": "Concept",
    "design": "Design|approval stage",
    "color_proof": "Color proof",
    "prototype": "Prototype",
    "pre_production_sample": "Pre-production sample",
    "final_sample": "Final sample",
    "packaging": "Packaging",
    "advertising": "Advertising",
    "mass_production_check": "Mass production check",
  },
  'approval_rounds.status': {
    "submitted": "Submitted",
    "in_review": "In review",
    "changes_requested": "Changes requested",
    "approved": "Approved",
    "rejected": "Rejected|approval",
    "withdrawn": "Withdrawn",
  },
  'approvals.stage': {
    "proposal": "Proposal",
    "concept": "Concept",
    "design": "Design|approval stage",
    "color_proof": "Color proof",
    "prototype": "Prototype",
    "pre_production_sample": "Pre-production sample",
    "final_sample": "Final sample",
    "packaging": "Packaging",
    "advertising": "Advertising",
    "mass_production_check": "Mass production check",
  },
  'approvals.status': {
    "submitted": "Submitted",
    "in_review": "In review",
    "changes_requested": "Changes requested",
    "approved": "Approved",
    "rejected": "Rejected|approval",
    "withdrawn": "Withdrawn",
  },
  'approvals.timeout_outcome': {
    "none": "None",
    "deemed_refused": "Deemed refused",
    "deemed_approved": "Deemed approved",
  },
  'approvals.copyright_check': {
    "unchecked": "Unchecked",
    "ok": "OK",
    "wrong": "Wrong",
  },
  'castings.role': {
    "voice": "Voice",
    "performer": "Performer",
    "motion": "Motion",
    "singing": "Singing",
    "voice_and_performer": "Voice and performer",
  },
  'character_assets.component': {
    "name": "Name",
    "logo": "Logo",
    "design_sheet": "Design sheet",
    "standing_art": "Standing art",
    "outfit": "Outfit",
    "live2d_model": "Live2D model",
    "model_3d": "3D model",
    "emote": "Emote",
    "voice": "Voice",
    "persona_lore": "Persona and lore",
    "jingle": "Jingle",
    "other": "Other",
  },
  'character_assets.acquisition': {
    "owned_original": "Created in-house",
    "work_for_hire": "Work made for hire",
    "assignment": "Assignment",
    "exclusive_license": "Exclusive licence",
    "nonexclusive_license": "Non-exclusive licence",
    "unknown": "Unknown",
  },
  'character_assets.portfolio_use': {
    "not_allowed": "Not allowed",
    "allowed": "Allowed",
    "after_announcement": "After announcement",
    "conditions": "Conditions",
  },
  'character_assets.status': {
    "planned": "Planned",
    "commissioned": "Commissioned",
    "delivered": "Delivered",
    "cleared": "Cleared",
    "needs_attention": "Needs attention",
  },
  'characters.kind': {
    "anime_character": "Anime character",
    "vtuber_persona": "VTuber persona",
    "virtual_singer": "Virtual singer",
    "mascot": "Mascot",
    "idol_member": "Idol group member",
    "game_character": "Game character",
    "other": "Other",
  },
  'characters.ownership_model': {
    "agency_owned": "Agency owned",
    "talent_owned": "Talent owned",
    "co_owned": "Co-owned",
    "licensed_in": "Licensed in",
    "committee_owned": "Committee owned",
  },
  'characters.status': {
    "development": "Development",
    "active": "Active",
    "hiatus": "Hiatus",
    "retired": "Retired",
    "archived": "Archived",
  },
  'clearances.item_type': {
    "original_work_license": "Original work licence",
    "script": "Script",
    "character_design": "Character design",
    "music_sync": "Music sync",
    "music_master": "Music master",
    "voice_cast": "Voice cast",
    "performer_consent": "Performer consent",
    "footage": "Footage",
    "artwork": "Artwork",
    "trademark_search": "Trademark search",
    "title_search": "Title search",
    "chain_of_title": "Chain of title",
    "committee_consent": "Committee consent",
    "ratings": "Ratings",
    "other": "Other",
  },
  'clearances.status': {
    "not_started": "Not started",
    "requested": "Requested",
    "in_progress": "In progress",
    "cleared": "Cleared",
    "cleared_with_risk": "Cleared with risk",
    "not_cleared": "Not cleared",
    "not_applicable": "Not applicable",
  },
  'committee_members.status': {
    "active": "Active",
    "transferred": "Transferred",
    "insolvent": "Insolvent",
    "exited": "Exited",
  },
  'committees.form': {
    "nin_i_kumiai": "Partnership (nin-i kumiai)",
    "spc": "Special purpose company",
    "llp": "LLP",
    "sole": "Single company",
    "co_production": "Co-production",
    "other": "Other",
  },
  'committees.status': {
    "forming": "Forming",
    "formed": "Formed",
    "production": "Production",
    "exploiting": "Exploiting",
    "term_review": "Term review",
    "dissolved": "Dissolved",
    "consolidated": "Consolidated",
  },
  'committees.lead_fee_base': {
    "gross": "Gross",
    "net": "Net",
  },
  'committees.consent_default': {
    "unanimous": "Unanimous",
    "majority": "Majority",
    "lead_discretion": "Lead company decides",
    "consult": "Consult members",
  },
  'consent_requests.status': {
    "open": "Open",
    "approved": "Approved|consent",
    "refused": "Refused|consent",
    "withdrawn": "Withdrawn",
    "expired": "Expired",
  },
  'content_id_assets.asset_type': {
    "sound_recording": "Sound recording",
    "composition": "Composition",
    "music_video": "Music video",
    "art_track": "Art track",
    "web": "Web",
  },
  'content_id_assets.policy': {
    "monetize": "Monetize",
    "track": "Track",
    "block": "Block",
  },
  'content_id_assets.status': {
    "active": "Active",
    "inactive": "Inactive",
    "conflict": "Conflict",
  },
  'content_id_claims.direction': {
    "incoming": "Claims on our videos",
    "outgoing": "Our claims",
  },
  'content_id_claims.status': {
    "open": "Open",
    "disputed": "Disputed|content id",
    "appealed": "Appealed",
    "released": "Released",
    "upheld": "Upheld",
    "expired": "Expired",
    "resolved": "Resolved",
  },
  'customs_recordations.jurisdiction': {
    "JP": "JP",
    "US": "US",
    "CN": "CN",
    "EU": "EU",
    "KR": "KR",
    "TW": "TW",
    "other": "Other",
  },
  'customs_recordations.status': {
    "preparing": "Preparing",
    "filed": "Filed",
    "accepted": "Accepted",
    "expired": "Expired",
    "withdrawn": "Withdrawn",
  },
  'deadlines.kind': {
    "hard": "Statutory",
    "extendable": "Extendable",
    "designated": "Office-set",
    "internal": "Internal",
    "reminder": "Reminder",
  },
  'deadlines.category': {
    "prosecution": "Prosecution",
    "filing": "Filing",
    "renewal": "Renewal",
    "opposition": "Opposition",
    "use": "Use",
    "term": "Term",
    "agreement": "Agreement",
    "copyright": "Copyright",
    "committee": "Committee",
    "talent": "Talent",
    "playbook": "Talent playbook",
    "licensing": "Licensing",
    "approval": "Approval",
    "music": "Music",
    "content_id": "Content ID",
    "enforcement": "Enforcement",
    "customs": "Customs",
    "permission": "Permission",
    "guideline": "Guideline",
    "other": "Other",
  },
  'deadlines.status': {
    "open": "Open",
    "done": "Done",
    "not_needed": "Not needed",
    "extended": "Extended",
    "missed": "Missed",
    "transferred": "Transferred",
    "cancelled": "Cancelled",
  },
  'deadlines.source': {
    "rule": "Rule",
    "office": "Office",
    "inbox": "Inbox",
    "manual": "Manual",
    "agreement": "Agreement",
    "system": "System",
    "playbook": "Playbook",
  },
  'distributions.status': {
    "draft": "Draft",
    "issued": "Issued",
    "paid": "Paid",
  },
  'documents.doc_type': {
    "office_action": "Office action",
    "filing": "Filing",
    "receipt": "Receipt",
    "certificate": "Certificate",
    "correspondence": "Correspondence",
    "contract": "Contract",
    "style_guide": "Style guide",
    "model_sheet": "Model sheet",
    "statement": "Statement",
    "invoice": "Invoice",
    "evidence": "Evidence",
    "specimen": "Specimen",
    "chain_of_title": "Chain of title",
    "guideline_snapshot": "Guideline snapshot",
    "customs": "Customs",
    "platform_notice": "Platform notice",
    "sample_photo": "Sample photo",
    "report": "Report",
    "other": "Other",
  },
  'documents.source': {
    "upload": "Upload",
    "office": "Office",
    "email": "Email",
    "agent": "Agent",
    "portal": "Portal",
  },
  'enforcement_cases.case_type': {
    "counterfeit": "Counterfeit",
    "impersonation": "Impersonation",
    "piracy": "Piracy",
    "unauthorized_derivative": "Unauthorized derivative",
    "clip_violation": "Clip guideline violation",
    "defamation": "Defamation",
    "harassment": "Harassment",
    "leak": "Leak",
    "ai_misuse": "AI misuse",
    "trademark_conflict": "Trademark conflict",
    "content_id": "Content ID",
    "other": "Other",
  },
  'enforcement_cases.forum': {
    "marketplace": "Marketplace",
    "dmca": "DMCA",
    "jp_platform": "Japanese platform request",
    "sender_disclosure": "Sender disclosure",
    "customs": "Customs",
    "criminal": "Criminal",
    "cease_desist": "Warning letter",
    "litigation": "Litigation",
    "coda": "CODA",
    "opposition": "Opposition",
    "cancellation": "Cancellation",
    "invalidation": "Invalidation",
    "platform_report": "Platform report",
    "other": "Other",
  },
  'enforcement_cases.role': {
    "offense": "Offense",
    "defense": "Defense",
  },
  'enforcement_cases.status': {
    "new": "New",
    "investigating": "Investigating",
    "notice_sent": "Notice sent",
    "takedown_requested": "Takedown requested",
    "removed": "Removed",
    "counter_noticed": "Counter noticed",
    "disclosure_requested": "Disclosure requested",
    "complaint_filed": "Complaint filed",
    "litigation": "Litigation",
    "settled": "Settled",
    "won": "Won",
    "lost": "Lost",
    "closed": "Closed",
    "monitoring": "Monitoring",
  },
  'events.source': {
    "manual": "Manual",
    "office": "Office",
    "inbox": "Inbox",
    "rule": "Rule",
    "system": "System",
    "portal": "Portal",
  },
  'evidence.kind': {
    "screenshot": "Screenshot",
    "page_archive": "Page archive",
    "test_purchase": "Test purchase",
    "listing": "Listing",
    "video": "Video",
    "document": "Document",
    "other": "Other",
  },
  'families.kind': {
    "design": "Design",
    "trademark": "Trademark",
  },
  'families.mark_type': {
    "word": "Word",
    "figurative": "Figurative",
    "combined": "Combined",
    "three_d": "3D",
    "colour": "Colour",
    "sound": "Sound",
    "motion": "Motion",
    "position": "Position",
    "pattern": "Pattern",
    "hologram": "Hologram",
    "multimedia": "Multimedia",
    "other": "Other",
  },
  'families.strategy': {
    "maintain": "Maintain",
    "review": "Review",
    "prune": "Trim classes or offices",
    "abandoned": "Abandoned",
  },
  'fan_registrations.kind': {
    "clip_channel": "Clip channel",
    "fan_permit": "Fan permit",
    "event_permit": "One-day event licence",
    "fan_game": "Fan game",
    "other": "Other",
  },
  'fan_registrations.applicant_type': {
    "individual": "Individual",
    "group": "Group",
    "corporate": "Corporate",
  },
  'fan_registrations.status': {
    "applied": "Applied",
    "approved": "Approved",
    "active": "Active",
    "rejected": "Rejected",
    "suspended": "Suspended",
    "expired": "Expired",
    "revoked": "Revoked",
  },
  'fee_schedule.entity': {
    "any": "Any",
    "large": "Large",
    "small": "Small",
    "micro": "Micro",
  },
  'franchises.kind': {
    "anime_title": "Anime title",
    "original_character": "Original character",
    "vtuber_agency": "VTuber agency",
    "vtuber_group": "VTuber group",
    "virtual_singer": "Virtual singer",
    "game": "Game",
    "music_project": "Music project",
    "mixed_media": "Mixed media",
    "other": "Other",
  },
  'franchises.ownership_model': {
    "committee": "Production committee",
    "sole_owner": "We own it",
    "licensed_in": "Licensed in",
    "co_production": "Co-production",
    "talent_owned": "Talent owned",
  },
  'franchises.status': {
    "development": "Development",
    "active": "Active",
    "dormant": "Dormant",
    "retired": "Retired",
  },
  'fx_rates.source': {
    "ecb": "ECB",
    "manual": "Manual",
  },
  'goods_services.class_status': {
    "pending": "Pending",
    "registered": "Registered",
    "refused": "Refused",
    "partially_refused": "Partially refused",
    "deleted": "Deleted",
    "cancelled": "Cancelled",
  },
  'grants.direction': {
    "in": "In",
    "out": "Out",
  },
  'grants.kind': {
    "grant": "Grant",
    "holdback": "Holdback",
    "restriction": "Restriction",
    "reservation": "Reservation",
    "window": "Window (madoguchi)",
  },
  'grants.fee_base': {
    "gross": "Gross",
    "net": "Net",
  },
  'guidelines.kind': {
    "fan_work": "Fan works",
    "clip": "Clips",
    "cover_song": "Cover songs",
    "ai_use": "AI use",
    "doujin_event": "One-day event licence",
    "corporate": "Corporate",
    "other": "Other",
  },
  'guidelines.status': {
    "draft": "Draft",
    "published": "Published",
    "superseded": "Superseded",
  },
  'ics_tokens.scope': {
    "mine": "Mine",
    "all": "All",
  },
  'inbox_items.kind': {
    "office_change": "Office change",
    "document": "Document",
    "agreement_draft": "Contract read",
    "royalty_statement": "Royalty statement",
    "permission": "Permission",
    "watch_hit": "Watch hits",
    "agent_proposal": "Proposal",
    "email": "Email",
  },
  'inbox_items.status': {
    "new": "New",
    "accepted": "Accepted",
    "partially_accepted": "Partly accepted",
    "rejected": "Rejected",
    "awaiting_second": "Waiting for second review",
  },
  'inbox_items.confidence': {
    "high": "High",
    "medium": "Medium",
    "low": "Low",
    "none": "None",
  },
  'inbox_items.source': {
    "office_sync": "Office sync",
    "agent": "Agent",
    "email": "Email",
    "user": "User",
    "portal": "Portal",
  },
  'involvements.role': {
    "original_author": "Original author",
    "author": "Author",
    "illustrator": "Illustrator",
    "modeler": "Modeler",
    "composer": "Composer",
    "lyricist": "Lyricist",
    "arranger": "Arranger",
    "publisher": "Publisher",
    "label": "Label",
    "producer": "Producer",
    "director": "Director",
    "screenwriter": "Screenwriter",
    "voice_actor": "Voice actor",
    "performer": "Performer",
    "singer": "Singer",
    "owner": "Owner",
    "applicant": "Applicant",
    "licensee": "Licensee",
    "licensor": "Licensor",
    "agent": "Agent",
    "committee_member": "Committee member",
    "counsel": "Counsel",
    "contributor": "Contributor",
    "other": "Other",
  },
  'matters.ip_type': {
    "trademark": "Trademark",
    "design": "Design",
  },
  'matters.route': {
    "national": "National",
    "regional": "Regional",
    "madrid": "Madrid",
    "hague": "Hague",
    "designation": "Madrid designation",
    "other": "Other",
  },
  'matters.relation': {
    "none": "None",
    "priority": "Priority",
    "designation": "Madrid designation",
    "divisional": "Divisional",
    "conversion": "Conversion",
    "related": "Related",
  },
  'matters.status': {
    "to_file": "To file",
    "filed": "Filed",
    "published": "Published",
    "examination": "Examination",
    "office_action": "Office action",
    "allowed": "Allowed",
    "opposed": "Opposed",
    "registered": "Registered",
    "in_grace": "In grace",
    "lapsed": "Lapsed",
    "abandoned": "Abandoned",
    "withdrawn": "Withdrawn",
    "refused": "Refused",
    "expired": "Expired",
    "revoked": "Revoked",
    "cancelled": "Cancelled",
    "transferred_out": "Transferred out",
  },
  'matters.status_group': {
    "pre_filing": "Before filing",
    "pending": "Pending",
    "live": "Live",
    "dead": "Dead",
  },
  'matters.tm_register': {
    "principal": "Principal",
    "supplemental": "Supplemental",
    "na": "Not applicable",
  },
  'matters.sync_source': {
    "none": "None",
    "uspto_tsdr": "USPTO TSDR",
    "euipo": "EUIPO",
    "jpo": "JPO",
  },
  'matters.sync_state': {
    "not_connected": "Not connected",
    "connected": "Connected",
    "error": "Error",
    "not_found": "Not found",
  },
  'notifications.kind': {
    "digest": "Digest",
    "escalation": "Escalation",
    "inbox": "Inbox",
    "sync": "Sync",
    "assignment": "Assignment",
    "approval": "Approval",
    "consent": "Consent",
    "portal": "Portal",
    "info": "Info",
  },
  'office_calendars.source': {
    "computed": "Computed",
    "official": "Official",
    "manual": "Manual",
  },
  'office_connections.office': {
    "uspto_tsdr": "USPTO TSDR",
    "euipo": "EUIPO",
    "jpo": "JPO",
  },
  'office_connections.status': {
    "not_configured": "Not configured",
    "connected": "Connected",
    "error": "Error",
    "paused": "Paused",
  },
  'parties.kind': {
    "person": "Person",
    "organization": "Organization",
  },
  'permissions.permission_type': {
    "game_title": "Game title",
    "music_work": "Music (composition)",
    "master": "Master recording",
    "backing_track": "Backing track",
    "arrangement": "Arrangement",
    "platform_blanket": "Platform blanket licence",
    "brand_tieup": "Brand tie-up",
    "cross_agency_collab": "Cross-agency collaboration",
    "venue": "Venue",
    "other": "Other",
  },
  'permissions.source': {
    "public_guideline": "Public guideline",
    "contract": "Contract",
    "application": "Application",
  },
  'permissions.archive': {
    "yes": "Yes",
    "live_only": "Live only",
    "no": "No",
  },
  'permissions.status': {
    "active": "Active",
    "pending_application": "Application needed",
    "expired": "Expired",
    "revoked": "Revoked",
    "suspended": "Suspended",
  },
  'platform_enrollments.platform': {
    "amazon_brand_registry": "Amazon Brand Registry",
    "mercari": "Mercari",
    "alibaba_ipp": "Alibaba IPP",
    "aidc_ipp": "AliExpress (AIDC IPP)",
    "ebay_vero": "eBay VeRO",
    "rakuten": "Rakuten",
    "yahoo_auctions": "Yahoo! Auctions",
    "youtube": "YouTube",
    "x": "X",
    "tiktok": "TikTok",
    "other": "Other",
  },
  'platform_enrollments.status': {
    "not_enrolled": "Not enrolled",
    "applying": "Applying",
    "active": "Active",
    "suspended": "Suspended",
    "expired": "Expired",
  },
  'products.occasion': {
    "regular": "Regular",
    "birthday": "Birthday",
    "anniversary": "Anniversary",
    "graduation": "Graduation",
    "event": "Event",
    "collab": "Collab",
    "campaign": "Campaign",
  },
  'products.sales_model': {
    "stock": "Stock",
    "made_to_order": "Made to order",
    "preorder": "Preorder",
    "lottery": "Lottery",
    "gacha": "Gacha",
    "prize": "Prize",
  },
  'products.stage': {
    "proposal": "Proposal",
    "contract": "Contract",
    "concept": "Concept",
    "design": "Design|approval stage",
    "prototype": "Prototype",
    "final_sample": "Final sample",
    "packaging": "Packaging",
    "mass_production": "Mass production",
    "on_sale": "On sale",
    "sell_off": "Sell-off",
    "ended": "Ended",
    "cancelled": "Cancelled",
  },
  'recordings.version_type': {
    "studio": "Studio",
    "tv_size": "TV size",
    "instrumental": "Instrumental",
    "a_cappella": "A cappella",
    "live": "Live|recording",
    "remix": "Remix",
    "cover": "Cover",
    "music_video": "Music video",
    "other": "Other",
  },
  'recordings.status': {
    "draft": "Draft",
    "mixing": "Mixing",
    "mastered": "Mastered",
    "released": "Released",
    "archived": "Archived",
  },
  'releases.format': {
    "digital_single": "Digital single",
    "digital_album": "Digital album",
    "cd_single": "CD single",
    "cd_album": "CD album",
    "vinyl": "Vinyl",
    "bluray_bundle": "Blu-ray bundle",
    "other": "Other",
  },
  'releases.status': {
    "planned": "Planned",
    "scheduled": "Scheduled",
    "released": "Released",
    "withdrawn": "Withdrawn",
  },
  'renewals.decision': {
    "pending": "Pending|decision",
    "renew": "Renew",
    "renew_partial": "Renew some classes",
    "lapse": "Lapse",
    "defer": "Defer",
  },
  'renewals.instruction_status': {
    "not_instructed": "Not instructed",
    "instructed": "Instructed",
    "paid": "Paid",
    "confirmed": "Confirmed",
    "lapsed": "Lapsed",
  },
  'royalty_reports.status': {
    "expected": "Expected",
    "received": "Received",
    "paid": "Paid",
    "disputed": "Disputed",
    "waived": "Waived",
  },
  'rules.base': {
    "event_date": "Event date",
    "filing_date": "Filing date",
    "priority_date": "Priority date",
    "publication_date": "Publication date",
    "registration_date": "Registration date",
    "expiry_date": "Expiry date",
    "signed_date": "Signed date",
    "term_end": "Term end",
    "graduation_date": "Graduation date",
    "debut_date": "Debut date",
    "valid_until": "Valid until",
    "end_date": "End date",
    "documents_valid_until": "Documents valid until",
  },
  'rules.offset_unit': {
    "calendar": "Calendar",
    "business": "Business",
  },
  'rules.kind': {
    "hard": "Hard",
    "extendable": "Extendable",
    "designated": "Designated",
    "internal": "Internal",
    "reminder": "Reminder",
  },
  'rules.category': {
    "prosecution": "Prosecution",
    "filing": "Filing",
    "renewal": "Renewal",
    "opposition": "Opposition",
    "use": "Use",
    "term": "Term",
    "agreement": "Agreement",
    "copyright": "Copyright",
    "committee": "Committee",
    "talent": "Talent",
    "playbook": "Playbook",
    "licensing": "Licensing",
    "approval": "Approval",
    "music": "Music",
    "content_id": "Content ID",
    "enforcement": "Enforcement",
    "customs": "Customs",
    "permission": "Permission",
    "guideline": "Guideline",
    "other": "Other",
  },
  'saved_views.scope': {
    "private": "Private",
    "shared": "Shared",
  },
  'saved_views.schedule': {
    "none": "None",
    "daily": "Daily",
    "weekly": "Weekly",
    "monthly": "Monthly",
  },
  'seal_orders.status': {
    "requested": "Requested",
    "issued": "Issued",
    "reconciled": "Reconciled",
    "cancelled": "Cancelled",
  },
  'settings.default_language': {
    "en": "English",
    "ja": "Japanese",
  },
  'settings.digest_channel': {
    "in_app": "In the app",
    "email": "Email",
    "slack": "Slack",
  },
  'settings.renewal_default': {
    "renew": "Renew",
    "lapse": "Lapse",
    "decide": "Decide",
  },
  'settings.default_signup_role': {
    "manager": "Manager",
    "rights": "Rights team",
    "licensing": "Licensing team",
    "talent_manager": "Talent manager",
    "contributor": "Contributor",
    "viewer": "Viewer",
  },
  'society_contracts.society': {
    "jasrac": "JASRAC",
    "nextone": "NexTone",
    "self": "Self-managed",
    "other": "Other",
  },
  'society_contracts.model': {
    "trust_all": "All works on trust",
    "per_work": "Work by work",
  },
  'society_registrations.society': {
    "jasrac": "JASRAC",
    "nextone": "NexTone",
    "self": "Self-managed",
    "other": "Other",
  },
  'society_registrations.status': {
    "draft": "Draft",
    "submitted": "Submitted",
    "code_issued": "Code issued",
    "registered": "Registered",
    "disputed": "Disputed",
    "withheld": "Withheld",
  },
  'songs.tie_up_use': {
    "none": "None",
    "opening": "Opening",
    "ending": "Ending",
    "insert": "Insert",
    "theme": "Theme",
    "character_song": "Character song",
    "bgm": "Background music",
    "other": "Other",
  },
  'songs.status': {
    "draft": "Draft",
    "splits_pending": "Splits pending",
    "registered": "Registered",
    "released": "Released",
    "archived": "Archived",
  },
  'sync_runs.trigger': {
    "scheduled": "Scheduled",
    "manual": "Manual",
    "import": "Import",
  },
  'sync_runs.status': {
    "running": "Running",
    "ok": "OK",
    "partial": "Partial",
    "error": "Error",
    "skipped": "Skipped",
  },
  'talents.talent_type': {
    "vtuber": "VTuber",
    "voice_actor": "Voice actor",
    "singer": "Singer",
    "actor": "Actor",
    "producer": "Producer",
    "other": "Other",
  },
  'talents.affiliation': {
    "ours": "Our talent",
    "external": "External",
  },
  'talents.lifecycle': {
    "audition": "Audition",
    "pre_debut": "Before debut",
    "active": "Active|talent",
    "hiatus": "Hiatus",
    "suspended": "Suspended",
    "graduation_announced": "Graduation announced",
    "graduated": "Graduated",
    "terminated": "Terminated",
    "alumni": "Alumni",
  },
  'talents.privacy_class': {
    "public": "Public",
    "restricted": "Restricted",
  },
  'titles.title_type': {
    "series": "Series",
    "season": "Season",
    "episode": "Episode",
    "film": "Film",
    "ova": "OVA",
    "special": "Special",
    "short": "Short",
    "original_manga": "Original manga",
    "original_novel": "Original novel",
    "game": "Game",
    "stage_play": "Stage play",
    "event": "Event",
    "stream": "Stream",
    "stream_archive": "Stream archive",
    "music_video": "Music video",
    "voice_product": "Voice product",
    "book": "Book",
    "illustration": "Illustration",
    "other": "Other",
  },
  'titles.rights_basis': {
    "owned": "Owned",
    "committee": "Committee",
    "acquired": "Acquired",
    "licensed_in": "Licensed in",
    "mixed": "Mixed",
  },
  'titles.status': {
    "development": "Development",
    "production": "Production",
    "announced": "Announced",
    "released": "Released|title",
    "archived": "Archived",
  },
  'titles.author_kind': {
    "individual": "Individual",
    "joint": "Joint",
    "corporate": "Corporate",
    "anonymous": "Anonymous",
    "film": "Film",
  },
  'users.role': {
    "admin": "Admin",
    "manager": "Manager",
    "rights": "Rights team",
    "licensing": "Licensing team",
    "talent_manager": "Talent manager",
    "contributor": "Contributor",
    "viewer": "Viewer",
    "licensee": "Licensee",
    "committee_member": "Committee member",
    "reviewer": "Reviewer",
  },
  'users.ui_language': {
    "en": "English",
    "ja": "Japanese",
  },
  'watch_hits.kind': {
    "trademark": "Trademark",
    "marketplace": "Marketplace",
    "impersonation": "Impersonation",
    "web": "Web",
  },
  'watch_hits.status': {
    "new": "New",
    "reviewing": "Reviewing",
    "dismissed": "Dismissed",
    "monitor": "Monitor",
    "escalated": "Escalated",
    "actioned": "Action taken",
  },
};
